### PR TITLE
chore(7354): remove account_statement report

### LINKED ISSUE #6164: Updates for the Account Statement report
Finance > Report > Account Statement

This not a report!  It appears to be a registry.  It should be moved out of the "Report" sub-menu

Note: I did not spend much time evaluating the various options for this item.

**Suggestions**
- The currency should default to the enterprise currency (or the cached currency selection)

### LINKED ISSUE #7354: Updates to Account Statement page
Requested updates to report
- `Finance>Rapports/Rélevé de compte`
- `Finance>Reports/Account Statement`

The following items are based on feedback on https://github.com/IMA-WorldHealth/bhima/pull/7336
- [ ] Since the report is for ONE account, add the account number and title on the top-right of the PDF report
- [ ] Fix duplicated filters on the PDF report (forgot to check this before merging the PR)
- [ ] If the account_id is not cached in AppCache, the report page should automatically open the filter search modal.
- [ ] Should the grand totals go into the credit/debit columns on the PDF report?  Where does the difference go?  Or add an extra line at the bottom with those numbers (like the report page)?  Or put those numbers in the top right of the PDF output under the account number and name?

Finally, why does this report generate different output that the "Account Statement Report (Single)"?

### PR DESCRIPTION
**Pull request by jniles**
Removes the unused account statement report, based on internal discussions and feedback from the field.

Closes #7354.
Closes https://github.com/IMA-WorldHealth/bhima/issues/6164.

### CODE REVIEW

**Review by mbayopanda — APPROVED** [review]
LGTM 👍🏽 

bors r+

**Comment by mbayopanda** [comment]
@jniles could you resolve the conflict, please

**Comment by jniles** [comment]
@mbayopanda done.

Note that Bors no longer works as the service was deprecated.  You can read more about it [here](https://bors.tech/newsletter/2023/04/30/tmib-76/).  Instead, the bors team recommends [merge queues that are built into Github](https://github.blog/2023-07-12-github-merge-queue-is-generally-available/).  If you liked the security that bors brought, you can turn the merge queue feature on for this repository.

**Review by jmcameron — APPROVED** [review]
The code changes look good.
I tested it and it works.

**Pull request merged**
