### PR TITLE
fix stock inventories report cmm

### LINKED ISSUE #5034: The CMM is not calculated for the report "[Stock] Articles en stock"
This issue is about the fact that the cmm calculation is done for "Articles en stock" registry but not for the report "[Stock] Articles en stock"

### PR DESCRIPTION
**Pull request by mbayopanda**
This PR fixes the issue #5034 

Close #5034

### CODE REVIEW

**Review by jmcameron — APPROVED** [review]
I tested this PR and it works fine.   I tried it with the default CMM algorithm (MSH) and then switched to another one.  In both cases, the "Items in Stock" and the "Stock Inventories/Articles en Stock" reports matched. 

Looks ready to go.

**Comment by mbayopanda** [comment]
bors try

**Comment by jniles** [comment]
Bors r+

**Pull request merged**
