### PR TITLE
Renaming fee center to cost center

### PR DESCRIPTION
**Pull request by mbayopanda**
This PR is related to #5878 and it is based on the PR of @jniles #5901 

**How to test**

A. For a fresh database built with `yarn build:db` : 
- Run: `npm run build:db` or `yarn build:db`
- Run: `npm run dev`
- Explore the cost center module in bhima

B. For an existing database based on the last release (or last version on the main branch)
- Update the main branch locally
- Build the database with the main branch
- `git checkout` to this branch
- Run: `npm run migrate` to build the migration file
- Run the migration file with mysql
- Run: `npm run dev`
- Explore the cost center module in bhima
-

### CODE REVIEW

**Review by jmcameron — COMMENTED** [review]
Bruce,

Great work!  It was a big job!

I noticed that there are still a couple of translation items to fix:
image


I had some problems with the migration process.  Since there is not content for the cost allocation tables (besides the predefined ones in bhima.sql), I suggest refactoring the migrate.sql file and drop and recreate the following tables rather than preserving the past migration steps:
- drop old cost_center_basis table and create new cost_center_allocation_basis table
- drop old cost_center_basis_value and create new cost_center_allocation_basis_value table
- and remove the related "RENAME TABLE" lines.

I would like to be able to start fresh, do 'yarn build:db' and then load the next/migrate.sql file and have it work cleanly.  

Once you do that, I suggest you try all the cost center functions and make sure they work.

**Review by jmcameron — APPROVED** [review]
Looks good to me.

I tested the new cost center functions and they seem to work.
I also ran unit tests and the integration test and they all ran without problems.

**Comment by mbayopanda** [comment]
> 
> 
> Looks good to me.
> 
> I tested the new cost center functions and they seem to work.
> I also ran unit tests and the integration test and they all ran without problems.

Thank you

**Pull request merged**
