### PR TITLE
docs: document stored procedures

### PR DESCRIPTION
**Pull request by jniles**
This PR goes further towards documenting stored procedures in BHIMA for future open source developers.   It partially addresses #2147.

### CODE REVIEW

**Comment by jniles** [comment]
@mbayopanda, since @DedrickEnc and I are traveling, can you take a look at this?

**Review by DedrickEnc — APPROVED** [review]
LGTM

**Comment by DedrickEnc** [comment]
We have many files for stored procedures. We should complete them with good comment like this.

**Comment by jniles** [comment]
Yay!  :+1:

**Pull request merged**
