### PR TITLE
Feature update requisition satisfaction rate

### LINKED ISSUE #7000: Satisfaction rate report
The analysis of the satisfaction rate of the drugs, is a report making it possible to evaluate the quantity ordered by the structures, the validated quantity and the quantity delivered

Modules to add
- It will be necessary to add the activation in the stock parameter of the requisition validation step
- It will be necessary to add a module allowing to proceed to the validation of the orders
- The delivery should now take into account the validated quantities

The report should display:
- Satisfaction rate by quantity granted
- Satisfaction rate by number of item granted

### PR DESCRIPTION
**Pull request by lomamech**
- Improvement of the automatic updates of requisitions modules
- Implementation of the validation step at the stock parameter level
- Addition of validated status for requisition requests
- Reactivation status processed for requisitions
- Assisted the validation of requisitions for actions related to a role
- Add a new column to display the "Validated quantity" column

- Update requisition integration test

closes https://github.com/IMA-WorldHealth/bhima/issues/7000

### CODE REVIEW

**Comment by lomamech** [comment]
**To be able to validate requisitions**
- You must first activate the option « Enable requisition validation step »
image
- The second step is to activate the “validate requisition requests” option to allow users to be able to validate requisitions
image

Once these two steps are done
image

For requisitions that are pending, the actions option allows you to validate the quantities ordered for each order.

image

The form used to validate the quantities ordered, displays the old quantity and a field

image

Once the validation is done, the requisition form looks like this.

image

**Review by mbayopanda — APPROVED** [review]
LGTM 👍🏽 

bors r+

**Comment by mbayopanda** [comment]
@lomamech es-ce que vous avez fini avec ce PR ?

**Comment by lomamech** [comment]
@mbayopanda  I'm already done with this Pull Request

**Comment by mbayopanda** [comment]
This PR also fixes the issue #6911 

bors r+

**Comment by jmcameron** [comment]
bors try

**Comment by jmcameron** [comment]
bors try

**Pull request merged**
