### PR TITLE
feat(nativation) authentification

### LINKED ISSUE #3334: Invoice Registry accessible even if a user does not have the right to access it.
Our permissions are broken when navigating between Patient Registry -> Invoice Registry.  For some reason, a user with rights to only see the Patient Registry can see the Invoice Registry via the grid link.

See example:

_Gif 1: Escaping the permissions restrictions via the ui-grid link_

This might happen to more modules - it should be thoroughly investigated.

### PR DESCRIPTION
**Pull request by jeremielodi**
This PR helps to make sure the user is allowed to access a specific page on the client side
close #3334

### CODE REVIEW

**Comment by jeremielodi** [comment]
I thought this is the right way to solve the client authentification problem but I realise that, in bhima, we have several type of urls. Some of the them are egal to the unit.path in the database but others are weird, like ``` url : /create```.  This last case are not eased to compare with unit.path

**Comment by jeremielodi** [comment]
To my mind it will be good to add a column in unit table named  ```state_name```, it will contain the angular route state for each unit record. This will allow us to check if a user as access to every path. The last think to check will be the sub states, for those, role_action may be used

**Comment by jniles** [comment]
@jeremielodi, that seems like a reasonable proposal.  I would remove the `/path` from the unit table if we are adding the state_name.  I also think the `url` field isn't used and you could remove that as well.

**Comment by jniles** [comment]
Superseded by #3380.

**Pull request closed without merging**
