### PR TITLE
Invalid404

### PR DESCRIPTION
**Pull request by lomamech**
Design for the invalid and unfound page

@jniles

### CODE REVIEW

**Comment by jniles** [comment]
@sfount, could you take a look at this and make sure it fits what you were interested in?  If so, the code could be improved.   But I want to make sure this is what you had in mind.

**Comment by sfount** [comment]
@jniles no problem - I'll take a look this afternoon.

**Comment by sfount** [comment]
@jniles @lomamech 
The functionality here looks great to me - it clearly demonstrates the 404 error state with a redirect. 

One comment would be that I recommend we simply use a `header` tag instead of an image for the 404 - this would be more consistenet with BHIMA's style. This can be updated when someone has time to design resources for the project.

_(Reference image)_


Another suggestion is that Controllers are not required for a valid route in Angular ui router, I believe the controller in this case can be removed.

**Comment by sfount** [comment]
@lomamech @IMA-WorldHealth/local-contributors This feature is to ensure users have a smooth redirect if they make a mistake - it will also help us in testing.

Do you think there should be a link to the home page or a back button to return to the previous state?

**Comment by sfount** [comment]
This pull request references https://github.com/IMA-WorldHealth/bhima-2.X/issues/285

**Comment by jniles** [comment]
@lomamech @sfount 

Thanks for the feedback.  It sounds like @sfount is okay with the changes and that the meet the criteria found in #285.

From a code perspective, here is what I recommend:
1. Try not specifying a URL in the `state` object.  If we could keep the same URL, then the user would know what URL didn't exist.  If that doesn't work, I think `/404` is a nicer URL.
2. The image does not add much value to the page - it looks out of place.  I recommend using HTML and CSS to form the 404 message.  It's much smaller for git to store (remember how much trouble we ran into with 1.x?)
3. You don't need a controller for the `404` state.

Once these changes are made, the code can be merged.  All the other ideas @sfount suggests are good ones, but we can add them in after this PR lands, if necessary.

**Comment by lomamech** [comment]
Removing of controller for error404, deleter the picture 404.png, update error404.html with the using of CSS

@jniles

**Comment by jniles** [comment]
@lomamech, looks good to me.  Could you write a quick end-to-end test that verifies that you can get to the 404 page?  After that, this can be merged.

**Comment by lomamech** [comment]
Adding the Test E2E for the tracking of error 404

@jniles

**Comment by jniles** [comment]
@lomamech  Thanks!  As soon as tests pass, I'll merge it.

**Pull request merged**
