### PR TITLE
Enhance chart of consumption report

### PR DESCRIPTION
**Pull request by mbayopanda**
This PR is related to #5418 

Here is the upgraded report config options : 
image

We have added the distribution option

Here is the upgraded graph : 
image

### CODE REVIEW

**Review by jmcameron — COMMENTED** [review]
I took skimmed the code. (J'ai parcouri le code.) It seemed okay.
When I loaded the IMCK data and tried it, it looks great except for one issue.  Please note that long inventory names are being cut off on the left.
image

I think there should be some way to force it to wrap text so that the text on the left is not lost.  It is also cut off in the PDF generated.  See attached.
[test.pdf](https://github.com/IMA-WorldHealth/bhima/files/6065049/test.pdf)

**Comment by jniles** [comment]
What is the relationship between this PR and https://github.com/IMA-WorldHealth/bhima/pull/5437?  It looks like some of the changes are identical.  Should one come before the other?

**Comment by mbayopanda** [comment]
@jniles the  #5437 report group data by type of flux (purchase, integration, distribution to patient, etc), the current report group just by inventories and data are restricted to (distribution to patient, distribution to service and distribution to depot)

**Comment by mbayopanda** [comment]
@jniles changes landed

**Comment by jniles** [comment]
@mbayopanda have you rebased against `refactor-stock-management`?  It looks like you've pull in some commits from @jmcameron somehow and that is likely breaking the tests.  Could you take a look?

**Pull request closed without merging**
