### PR TITLE
Improved purchase order module

### LINKED ISSUE #6929: Improved purchase order module
- Allow the display of funds with at least four digits with the comma
- Add the possibility to mention the name of the person making the purchase request
- Add a new register to display purchase orders in detail

### PR DESCRIPTION
**Pull request by lomamech**
- Display of purchase cost with 4 decimals
- Added the possibility to select the person responsible for the purchase order
- Added new purchase order register with details
- Add importation file in format PDF and xlsx

closes #6929

### CODE REVIEW

**Comment by lomamech** [comment]
image

**Review by mbayopanda — APPROVED** [review]
A useful tool, great job @lomamech 👍🏽 

LGTM

**Comment by mbayopanda** [comment]
bors try

**Comment by lomamech** [comment]
@mbayopanda  All checks have passed

**Pull request merged**
