### PR TITLE
Add created_at to fix the quantity calculation in stock dataset for test

### PR DESCRIPTION
**Pull request by mbayopanda**
This PR fixes values of ordered stock movement in the stock dataset

Here are the previous values
Capture d’écran 2020-10-29 à 12 18 50

Here are the fixes
Capture d’écran 2020-10-29 à 12 07 48

Which help to understand the calculation of CMM
 
Capture d’écran 2020-10-29 à 12 19 11

### CODE REVIEW

**Comment by jmcameron** [comment]
bors try

**Review by jniles — APPROVED** [review]
LGTM.

bors r+

**Pull request merged**
