### PR TITLE
perf(uiGrid): use performance feats where possible

### LINKED ISSUE #1039: (perf): use flatEntityAccess for the majority of our grids
One useful performance increase might be to enabled `flatEntityAccess` for the majority of our grids, particularly the registries.  Since we are not mutating data at all in these pages, there is no need to do large , nested traversals of the dataset.

[Reference Documentation](http://ui-grid.info/docs/#/tutorial/404_large_data_sets_and_performance).

### PR DESCRIPTION
**Pull request by jniles**
This commit changes the majority of the ui-grids to use
`flatEntityAccess` and `fastWatch` where possible.  This includes all of
the registries.

It also adds the `ngTouch` module for better behavior on mobile.

Closes #1039.

---
Thank you for contributing!

Before submitting this pull request, please verify that you have:
 - [x] Run your code through JSHint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
 - [x] Run integration tests.
 - [x] Run end-to-end tests.
 - [x] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

### CODE REVIEW

**Comment by sfount** [comment]
Were you able to test the performance difference on on mobile after importing the `ngTouch` library? 

I'm not sure if there are specific changes to grid configurations we need to make to make full use of this but it would be good to make sure we know how the performance is now so that we can somewhat measure this difference.

**Comment by jniles** [comment]
@sfount, no I never succeeded.  I'll take a look into this when I get a chance to spin up my own network.

**Review by sfount — APPROVED** [review]
Code LGTM. This work should benefit all of our work with grids.

**Comment by jniles** [comment]
@sfount, I did test this on my Zuk Z1 yesterday and it is snappy on older hardware.  You can confirm on your own phone, but there were no significant performance regressions on my end and potentially a performance benefit.

That being said, I haven't used the app on mobile enough to be sure if the `ngTouch` alone made a performance difference.

**Pull request merged**
