### PR TITLE
Patient Find Directive

### PR DESCRIPTION
**Pull request by mbayopanda**
This PR : 
- Refactor Patient Find Directive
- Add Find Patient Directive with Inline type
- Add Find Patient Directive with Panel type

### CODE REVIEW

**Comment by mbayopanda** [comment]
@jniles The last commit in this PR has some style in the template file of the Find Patient Directive. I'm waiting for any other tasks that i can do. Thanks

**Comment by jniles** [comment]
@mbayopanda, thanks - will review.

**Comment by jniles** [comment]
LGTM.

**Comment by jniles** [comment]
@DedrickEnc, could you assign @mbayopanda another task?  This one is completed to satisfaction.

**Pull request merged**
