### PR TITLE
Update setup-migration-script.sh

### PR DESCRIPTION
**Pull request by jniles**
This commit fixes the migration script to solve the break introduced by the stored procedure rework.

### CODE REVIEW

**Review by jmcameron — CHANGES_REQUESTED** [review]
Sorry to report that this was not enough. When trying to do a migration, I fetch the DB, build the DB, do 'npm run migrate' and then try to load the migration file and get this error:

```ERROR 1451 (23000) at line 5033: Cannot delete or update a parent row: a foreign key constraint fails (`semi`.`role_unit`, CONSTRAINT `role_unit__unit` FOREIGN KEY (`unit_id`) REFERENCES `unit` (`id`) ON UPDATE CASCADE)```

I'll attach a prior version of the migration file (from before this PR) that has lines commented out that eventually let me use it.

[migration-semi.sql.txt](https://github.com/IMA-WorldHealth/bhima/files/12645091/migration-semi.sql.txt)

**Comment by jniles** [comment]
@jmcameron , as discussed on WhatsApp, this has more to do with the migration scripts than the shell file here.  I ran into a similar thing while testing with the HEV database.

It might be a quick fix (something missing from migrate.sql) or it might be a longer fix (something changed in MySQL's handing of FKs/triggers).  I don't have the bandwidth for this at present, so would be happy for someone else to look into it.

**Comment by jmcameron** [comment]
Updated the next/migration.sql file to get this working.

**Pull request merged**
