### PR TITLE
refactor(service) : Use service as depot for stocks

### LINKED ISSUE #1489: (feature) Update service management with the consideration of depot for service
This issue is about to add the depot management module and implement the depot for service (at the creation of service).

The questions here are : 
- How can we track medicines distribution to patient in a given service ?
- Which quantity of medicines could we give to a service as its stock ?
- What is the quantity of medicines in a service ?

The proposal is to add the `service_uuid` column in the `depot` table, so the distribution to a service will be just a movement to another depot (service depot).

In this way, we can easily answer to questions above : 

medicines is stock

stock report

Preoccupation: 
- What happen if the service's depot is deleted ?

An answer for this preoccupation is to progammatically avoid this kind of deletion with a SQL CONSTRAINT

### PR DESCRIPTION
**Pull request by mbayopanda**
This PR : 
- Refactor the Service module according the BHIMA-2.X standards and auto creation of depot when create a new service
- Refactor the Depot module according the BHIMA-2.X standards
- Update Stock Modules for using services as depots
- Update Stock Receipts for services as depots movements
- Upgrade e2e tests for services and stocks
- Update integration tests for depots, services and stocks
- Update depot schema by adding a new column `service_uuid`

Close #1489

### CODE REVIEW

**Comment by mbayopanda** [comment]
@DedrickEnc could you review this PR ?

**Comment by DedrickEnc** [comment]
@mbayopanda
Can you rebase this branch first?

**Comment by mbayopanda** [comment]
@DedrickEnc i did it

**Comment by mbayopanda** [comment]
@DedrickEnc @jniles could you review this PR, please.

**Comment by DedrickEnc** [comment]
@mbayopanda @jniles
We had a discussion about this PR and both of you planed to discuss again about this PR. So I would like to know your conclusion (eventually the why of your conclusion) before eventually review or not this PR.

**Review by jniles — COMMENTED** [review]
I believe the conclusion of the team's discussion was to remove the link between the depots and services.

Looking at the code, the depot management module refactor looks really good.  The updates to services also look very good. :+1:

I propose that the depot_uuid be removed from the services, as well as the refactors in `bhDepotDropdown`.  Otherwise, the rest of the code looks really good!

**Comment by mbayopanda** [comment]
I sent two PRs #2032 and #2033 which refactor service and depot modules, so this PR can be closed.

**Pull request closed without merging**
