### PR TITLE
Fix the testing period for aggregated consumption

### LINKED ISSUE #5600: E2E test broken in master
This issue is about the test `Prevent negative stock quantities when Aggregate Consumption greater than the quantity available on current depot` which fails due to its calculated date

### PR DESCRIPTION
**Pull request by mbayopanda**
This PR fixes issue #5600 

Close #5600

### CODE REVIEW

**Comment by jniles** [comment]
Ran the tests.  This fixes it.  It was probably Feb with 28 days that threw us off...

bors r+

**Comment by jniles** [comment]
bors try

**Comment by jmcameron** [comment]
I tried running the tests on my laptop.   The integration tests passed, but I see a failure in the Stock integration test:

image

The end-to-end tests passed.  So the only test that failed is the "Stock Integration" test.

**Comment by jmcameron** [comment]
> I tried running the tests on my laptop. The integration tests passed, but I see a failure in the Stock integration test

I wonder if this is because April only has 30 days?

When I look at the failure, I see (in depot.js:106) that the expected values are:
      values = {
        algo_def : 33.27,
        algo_msh : 33.15,
        sum_days : 365,
        sum_stock_day : 275,
        sum_consumption_day : 8,
        sum_consumed_quantity : 300,
        number_of_month : 12,
        sum_stock_out_days : 90,
        head_days : 0,
      };
But the actual values (from res.body) are:
        algo_def : 33.15,
        algo_msh : 33.93,
        sum_days : 365,
        sum_stock_day : 276,
        sum_consumption_day : 8,
        sum_consumed_quantity : 300,
        number_of_month : 12,
        sum_stock_out_days : 89,
        head_days : 0,

When I checked the CMM calculations they are correct based on the difference in the value of 'sum_stock_out_days'.  So I think this is the key to the problem.

**Comment by jmcameron** [comment]
I was able to git this test working by converting the calculations of expiration dates based on DAY's (not MONTH's) in the stock SQL and updating the depot test file.  I modified these files (renamed, attached)
        modified:   test/data/service-stock.sql
        modified:   test/integration-stock/depots.js
[service-stock.sql.txt](https://github.com/IMA-WorldHealth/bhima/files/6424263/service-stock.sql.txt)
[depots.js.txt](https://github.com/IMA-WorldHealth/bhima/files/6424264/depots.js.txt)

@jniles and @mbayopanda : Please try these files and see if they work on your system.  If so, this seems like the correct approach since it guarantees the same number of days for the tests/expirations/etc regardless of whether months have different numbers of days.   However I think I may something may need further fixing because the "head_days" changed from 0 to 29 for the tests.

**Comment by mbayopanda** [comment]
> I tried running the tests on my laptop. The integration tests passed, but I see a failure in the Stock integration test:
> 
> image
> 
> The end-to-end tests passed. So the only test that failed is the "Stock Integration" test.

@jmcameron what is your environment configuration (MySQL version, Node version, OS) because the integration tests passed on my configuration (MySQL 5.7 and 8, Node 16.0.0, Windows 10.

You're right Sir, the `Stock Integration Tests` failed on both MySQL 5.7 and 8, the good news is that the updates you made fix the tests. Thank you 👍🏽

**Comment by mbayopanda** [comment]
> I was able to git this test working by converting the calculations of expiration dates based on DAY's (not MONTH's) in the stock SQL and updating the depot test file. I modified these files (renamed, attached)
> modified: test/data/service-stock.sql
> modified: test/integration-stock/depots.js
> [service-stock.sql.txt](https://github.com/IMA-WorldHealth/bhima/files/6424263/service-stock.sql.txt)
> [depots.js.txt](https://github.com/IMA-WorldHealth/bhima/files/6424264/depots.js.txt)
> 
> @jniles and @mbayopanda : Please try these files and see if they work on your system. If so, this seems like the correct approach since it guarantees the same number of days for the tests/expirations/etc regardless of whether months have different numbers of days. However I think I may something may need further fixing because the "head_days" changed from 0 to 29 for the tests.

The tests works correctly now on my machine 👍🏽

**Review by jniles — APPROVED** [review]
Looks good to me.  Great fix @jmcameron 

bors r+

**Pull request merged**
