### PR TITLE
improve(Account Reference)

### LINKED ISSUE #3877: Improvement of Accounts References Unit
Improvement of the Unit Account Reference is a very important module in the BHIMA system, this issue proposes to add the menu to make the quick search but also for ease the management of account references.

### PR DESCRIPTION
**Pull request by lomamech**
- Add the seach option for Registry of Account Reference
- Add the component bh-filters for display the filters and cache the
  filters
- Update API for Account Reference Add the filtes parser
- Update Integration and E2E test for Account Reference

closes #3877

### CODE REVIEW

**Comment by lomamech** [comment]
@jniles @mbayopanda @jeremielodi  please review this PR

**Review by jeremielodi — APPROVED** [review]
LGTM, good work @lomamech

**Pull request merged**
