### PR TITLE
feat(barcode): add barcodes to patient card

### PR DESCRIPTION
**Pull request by jniles**
This commit adds barcode functionality via handlebars to the patient card.  Currently it only encodes a simple UUID, which ought to be searchable via the patient search.

This commit requires review to make sure it is installable on windows.  There are some pretty heavy dependencies on graphics emulation.

Requires `npm install`!

@DedrickEnc @mbayopanda could you try to install this and run the tests before I merge?  It requires quite a bit of work to get it up and running on windows.  See [this link](https://github.com/Automattic/node-canvas/wiki/Installation---Windows) to install the dependencies.

[PatientCard.pdf](https://github.com/IMA-WorldHealth/bhima-2.X/files/478956/PatientCard.pdf)
Produces the above document.

---

Thank you for contributing!

Before submitting this pull request, please verify that you have:
- [x] Run your code through JSHint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
- [x] Run integration tests.
- [x] Run end-to-end tests.
- [x] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

### CODE REVIEW

**Comment by jniles** [comment]
@dedrickenc @mbayopanda any feedback?  Did you get it working on Windows?

**Comment by mbayopanda** [comment]
@jniles i have some problem to build the application : 

I make a `npm install` to install dependencies but i have : 

error build

When i run `npm run dev_windows`

**Comment by jniles** [comment]
@mbayopanda, did you follow all these steps?

https://github.com/Automattic/node-canvas/wiki/Installation---Windows

If so, then we can look into it next week ... but it is not very important.

**Comment by jniles** [comment]
I'm closing this as out of the current development cycle's scope.  We can work out these more advanced features later.

**Pull request closed without merging**
