### PR TITLE
feat(ci): add callbacks for robot to build travis

### PR DESCRIPTION
**Pull request by jniles**
This commit adds callback hooks for an instance of homu located at
kwilu.bhi.ma to build/run Travis CI hooks on build failure.  The robot
will also be responsible for assigning reviewers and the like.

-----

Thank you for contributing!

Before submitting this pull request, please verify that you have:
 - [x] Run your code through ESLint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
 - [x] Run integration tests.
 - [x] Run end-to-end tests.
 - [x] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

### CODE REVIEW

**Comment by jniles** [comment]
@kwilu p=1

**Comment by jniles** [comment]
@kwilu r+

**Comment by jniles** [comment]
@kwilu p=0

**Comment by jniles** [comment]
@kwilu r+

**Comment by jniles** [comment]
@kwilu r+

**Comment by ghost** [comment]
:pushpin: Commit cccdd83 has been approved by `jniles`

**Comment by jniles** [comment]
@kwilu retry

**Comment by ghost** [comment]
:hourglass: Testing commit cccdd8395b3de253893fd9e968178811626762bd with merge d98e7a9dcd6b849cadf2988801b49fa89906ba1b...

**Comment by ghost** [comment]
:hourglass: Testing commit cccdd8395b3de253893fd9e968178811626762bd with merge 7ad96d3e50c1962a54158d845c554a223d312a09...

**Comment by jniles** [comment]
I'm thinking that @kwilu isn't responding because the hooks aren't merged into master yet.  Merging...

**Pull request merged**
