### PR TITLE
fix(reports): select patient before submit

### LINKED ISSUE #5611: Patient Standing Report problem
In Hospital > Reports  > Patient Standing Report
if you click on [Preview], the field for Patient Name is bordered in red but the preview still works --> but fails with a 404 error.  
The form needs to be fixed so that the [Preview] button is disabled until a patient name is selected.

Probably a good idea to check for similar issues with the Employee Standing Report.

### PR DESCRIPTION
**Pull request by jniles**
Fixes the bug in the patient standing report where the report could be submitted even without a fix in the patient standing report.

Closes #5611.

### CODE REVIEW

**Review by jmcameron — APPROVED** [review]
The code changes look good.

I tested it and it works correctly.

**Comment by jmcameron** [comment]
Sorry, can't help.  These tests pass on my machine!

**Comment by jniles** [comment]
bors try

**Comment by jniles** [comment]
For some reason, I have the magic fingers!

bors r+

**Pull request merged**
