### PR TITLE
chore: remove odk-central plugin

### LINKED ISSUE #6671: Add an xlsForm for "PV de reception"
This issue is about to add a upgraded xlsForm in BHIMA which will allow to collect data from FOSA during their reception of medicines.

Here is a sample of an xlsForm for asset
[pv-reception-assets.xlsx](https://github.com/IMA-WorldHealth/bhima/files/8870493/pv-reception-assets.xlsx)

The goal is to have an xlsForm for medicines reception, for example an IT of a FOSA can enter in ODK Collect data of a reception : 
- The depot name
- Number of products received
- The inventory code of the product
- The lot number of the product
- The quantity for the given lot 

Once all these data are recorded and sent to Central, in BHIMA we must find this movement in the movement registry.

In BHIMA we must find a way to handle duplication of submissions so that even we have duplicated data in ODK Central, we must have in BHIMA unique movement to guarantee quality of data.

### LINKED ISSUE #6672: Add an xlsForm for "Consumption" in FOSA
Assume that we are in the context of a FOSA (Formation Sanitaire) and we have ODK Collect to collect data of consumption of medicines. 

This form will allow us to collect data of consumption of medicines in the FOSA, these data will be sent to ODK Central and then synchronized with BHIMA to populate the stock movement table for the FOSA with the goal of having the CMM of the FOSA in real time.

### LINKED ISSUE #7190: Remove ODK Central integration from BHIMA
We no longer need to have ODK Central integration in BHIMA.  It is no longer used and the current plan is to use the BHIMA mobile application (https://github.com/IMA-WorldHealth/bhima_stock) for offline stock management.

I propose that we remove all the ODK Central integration code.  It is just more code to maintain at this point without a clear use-case.  At this point in the project, we should aim to reduce the maintenance burden as much as possible.

@mbayopanda @jmcameron what do you think?

Closing this issue would also close https://github.com/IMA-WorldHealth/bhima/issues/6671 and https://github.com/IMA-WorldHealth/bhima/issues/6672.

### PR DESCRIPTION
**Pull request by jniles**
Removes all references to ODK Central in the code base.  Adds migration scripts to drop ODK Central tables.

Closes #7190.
Closes #6672.
Closes #6671.

### CODE REVIEW

**Comment by mbayopanda** [comment]
@jniles could you fix the conflict so that we can merge this PR?

**Comment by jniles** [comment]
@mbayopanda done!

**Comment by jmcameron** [comment]
I discussed this with Bruce and he suggested that we set up the code for the ODK central plugin in a separate github repository before removing it from Bhima.

**Comment by jniles** [comment]
I am not totally sure I understand.  The code will always be there in the git history, and the ODK api is already in https://github.com/IMA-WorldHealth/odk-central-api-cjs/, though no one is maintaining it.  I don't have time to maintain it myself.

So ... what needs to be transferred?  And what purpose will it serve?

If there isn't an interest in this PR, I can just close it as well, no harm done.

**Comment by mbayopanda** [comment]
@jniles Since we have this repository https://github.com/IMA-WorldHealth/odk-central-api-cjs/ we can remove the code from BHIMA, my concern was about losing all the work we have done with this API. I forgot we had a repository for that. Thank you for your feedback. 

@jmcameron you can go on merging this PR.

**Pull request merged**
