### PR TITLE
Update sql for fix the sort in Fiscal Year list

### PR DESCRIPTION
**Pull request by lomamech**
Update sql for fix the sort in Fiscal Year list

@jniles

### CODE REVIEW

**Comment by jniles** [comment]
How does this fix the sort order?  What was the previous bug?

If there was a bug, please include an integration test to show that the bug has been fixed.

This change introduces an SQL injection vulnerability.  You must escape the parameters passed in to your SQL.  In this form, I cannot accept this PR into the repository.

**Comment by lomamech** [comment]
I will try to add an integration test but this code
  if (req.query.detailed === '1') {
    params = params.concat(req.session.enterprise.id);

```
sql =
  `SELECT f.id, f.enterprise_id, f.number_of_months, f.label, f.start_date, 
   f.previous_fiscal_year_id, f.locked, f.created_at, f.updated_at, f.note, DATE_ADD(start_date, INTERVAL number_of_months MONTH) AS end_date, 
   f.user_id, u.first, u.last
   FROM fiscal_year AS f
   JOIN user AS u ON u.id = f.user_id
   WHERE f.enterprise_id = ? `;

if(req.query.by && req.query.order){
  params = params.concat(req.query.by, req.query.order);
  sql += ` ORDER BY ? ?;`;
}
```

  // execute the query  
  } else {
    sql =
      'SELECT id, label FROM fiscal_year';
  }

  // execute the query
  db.exec(sql, params)
  .then(rows => {
    res.status(200).json(rows);
  })
  .catch(next)
  .done();
}
Do not allow the sorts

**Comment by jniles** [comment]
That is because the `?` escapes values, not columns.  [Here is the documentation](https://github.com/felixge/node-mysql#escaping-query-values).

Your original function would do format the SQL like this:

``` sql
ORDER BY "column" "DESC";
```

.. which mysql ignores instead of generating an error.

The correct fix would be something like this:

``` js
// make sure we do not inject data from the client.  Defaults to 'desc' for unrecognized 
// sort orders.  If we wanted to be really strict, we could return an error to the client.
const direction = (req.query.order === 'ASC') ? 'ASC' : 'DESC';

// nicely escape the column name, and put in the direction variable
// we use the two question marks (??) to escape column names, as shown in the
// node-mysql documentation.
params.push(req.query.by);
sql += ` ?? ${direction} `;

// ..  later on...

db.exec(sql, params);
```

**Comment by lomamech** [comment]
Fix and Improve the SQL the sorting Fiscal Year List

@jniles

**Comment by jniles** [comment]
LGTM.

**Pull request merged**
