### PR TITLE
Delete account management

### PR DESCRIPTION
**Pull request by lomamech**
Fix and Improve the Account Management

@sfount  @mbayopanda

### CODE REVIEW

**Review by sfount — COMMENTED** [review]
This looks like a good implementation of deleting accounts. It is great that it factors in account children for title accounts (as these will never be used in transactions in the posting journal/ general ledger). 

I do not think this pull request should implement account locking functionality. 

**Account Locking**
screenshot 2016-10-28 at 13 12 25

This locking feature has been proposed https://github.com/IMA-WorldHealth/bhima-2.X/issues/490 and has many implications on accounting functionality. 

If this pull request can focus on account deletion I think that would be best.

**Review by mbayopanda — COMMENTED** [review]
@sfount i review this `pull request` all things LGTM, only the locking checkbox for account is not pretty as ui.

Another thing is about to display or not locked accounts, maybe it require a new issue but i think we must have a mean to display only accounts which are not locked and if possible all accounts (locked or not).

**Comment by sfount** [comment]
@mbayopanda Thanks for the review. 
@lomamech Please seperate the account locking from this pull request before it is merged.

**Comment by mbayopanda** [comment]
@lomamech could refactor you PR according @sfount suggestions, if it's already done please update this branch

**Comment by lomamech** [comment]
@mbayopanda  i have yet remove the way to lock an account

**Review by mbayopanda — APPROVED** [review]
@sfount this PR works well and codes are good for the deletion of an account. We can merge it.

**Comment by jniles** [comment]
It looks like the account locking code was removed from this PR.  LGTM :+1:.

**Pull request merged**
