### PR TITLE
Feature delete inventory types groups units

### PR DESCRIPTION
**Pull request by troyev**
This pull request is originally from Vanga-Hospital/bhima-2.X. Moving it to IMA-WorldHealth/bhima-2.X per @jniles.

-----

This commit it to add the feature described here:
Implement DELETE on Inventory Types, Groups, and Units #96
https://github.com/Vanga-Hospital/bhima-2.X/issues/96

I ran jshint . at the top level directory, and it put out messages for other files, but not the ones changed in this commit.

I will need more specific direction on the integration tests to get those running smoothly. It seems to successfully create the database and succeed on some tests, but there are hundreds of failures in components unrelated to this commit. So I am not sure if that is expected, or there is something wrong with my setup. Similar experience with end-to-end tests.

Thanks,
Troy

---

Thank you for contributing!

Before submitting this pull request, please verify that you have:
 - [ ] Run your code through ESLint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
 - [ ] Run integration tests.
 - [ ] Run end-to-end tests.
 - [ ] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

### CODE REVIEW

**Review by jniles — COMMENTED** [review]
@troyev  great work!  The integration tests pass, the code is concise and readable.  I've pulled your code onto my local machine and it works as expected.

One last push on this will clean it up nicely.
 1. Your end to end tests get confused because the labels are updated before they can be deleted.  So, instead of 
 ```js
element(by.css('[data-delete-group="' + group.code +'"]')).click();
 ```
 ... the code should read ...
 ```js
element(by.css('[data-delete-group="' + updateGroup.code +'"]')).click();
 ```
 The same case holds for the other two tests.

To test these in isolation, you can add change the `describe('Inventory Configuration')` to `describe.only('Inventory Configuration')` at the top of your tests.  Only this `describe()` block will then run.  Be sure to change it back before submitting another PR though!

 2. Our users do not necessarily have the best eyesight or literacy.  For this reason, we try to color all our "delete" action red.  If you add the class `class="text-danger"` to your `<a>` element, it should color it red and be a good visual differentiator.

Thanks!

**Comment by jniles** [comment]
@troyev, just checking in - is there anything we can do get help get this in?

**Comment by troyev** [comment]
@jniles I think the commits from March 3 should do it. Are you able to see the code with the red links and fixed tests? Just let me know if there's something I need to do before you can merge it

**Comment by jniles** [comment]
@troyev, thanks a ton!  I've finally got back from the field and was able to merge your changes.  Great work!

**Pull request merged**
