### PR TITLE
Stock: cmm tests

### PR DESCRIPTION
**Pull request by jniles**
This PR builds a tests database with relative dates to ensure that the CMM continues to work into the future.

### CODE REVIEW

**Review by mbayopanda — COMMENTED** [review]
Tests are succeeding also when we have changed dates 👍 

I have just notice in the "Fiche de stock" report, data are not ordered correctly.

image

**Comment by jniles** [comment]
@mbayopanda tests pass!

**Comment by jniles** [comment]
bors try

**Comment by jmcameron** [comment]
bors try

**Comment by mbayopanda** [comment]
bors try

**Pull request merged**
