### PR TITLE
feature(Add new information for asset management)

### LINKED ISSUE #6783: Added new information for asset management
**Added new information for asset management**
After analyzing a registry of assets,
We realized that there was missing information, but necessary for the managers,

Reasons why it is necessary to add the following properties
- Year or Date of acquisition (This could be obtained automatically for the cases where one proceeds by the entry of stock by purchase order)
- The possibility of displaying the number of years of life based on the data of the date or the year of acquisition.
- The depreciation rate
- The value depreciated by depreciation (Purchase cost * Depreciation rate)
- Residual Accounting value (Cost of purchase - Depreciated value)

image

### PR DESCRIPTION
**Pull request by lomamech**
- Manage Depreciation rates for asset

closes #6783

To test this branch
- You must first define the depreciation rate for the inventory groups

- When batches are put into stock for inventories that are assets, the acquisition date must be defined

- With the depreciation rate and the date of acquisition, the fixed assets register makes the following calculation
1. **Year of life**: By calculating the difference between the acquisition date and the current year
2. **The depreciation percentage** by multiplying the depreciation rate defined at the level of the inventory group and the year of life
3. **The depreciated value** by multiplying the depreciation percentage by the purchase cost

4. **The book value** by subtracting the purchase cost from the depreciated value

### CODE REVIEW

**Comment by lomamech** [comment]
image

**Comment by lomamech** [comment]
@mbayopanda @jmcameron You can also import from csv files that it is either for inventories but also for stocks

**Comment by lomamech** [comment]
@mbayopanda @jmcameron this PR is ready for review

**Comment by mbayopanda** [comment]
@lomamech could you update this branch ?

**Comment by lomamech** [comment]
@mbayopanda the PR is Updated

**Pull request merged**
