### PR TITLE
improvement(Logistics documents)

### LINKED ISSUE #7168: Improved display of certain documents
This issue suggests:
- add the area for the supplier's signature
- add the stock movement reference on the shipping note

### PR DESCRIPTION
**Pull request by lomamech**
- Add suppliers signature area in receipt of purchase
- Add Stock movement reference on the shipment documents

closes #7168

### CODE REVIEW

**Comment by lomamech** [comment]
_Supplier_
image

_Reference movement_
image

image

image

**Review by jmcameron — APPROVED** [review]
Looks good.  I tested it and it works fine.

**Pull request merged**
