### PR TITLE
Using a simple reference number to search for a patient

### PR DESCRIPTION
**Pull request by DedrickEnc**
This PR is giving the possibility to the user searching a patient by providing the reference value directly. it closes https://github.com/Vanga-Hospital/bhima-2.X/issues/131
Thank you for contributing!

Before submitting this pull request, please verify that you have:
 - [x] Run your code through JSHint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
 - [x] Run integration tests.
 - [x] Run end-to-end tests.
 - [x] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

### CODE REVIEW

**Comment by DedrickEnc** [comment]
@sfount can I get a review?

**Comment by DedrickEnc** [comment]
The original PR is this #1134

**Comment by DedrickEnc** [comment]
@sfount I updated the PR

**Review by sfount — APPROVED** [review]
LGTM. Great work 👍

**Comment by sfount** [comment]
A note that continuous integration is currently not working - this has been verified to pass tests locally.

**Pull request merged**
