### PR TITLE
(feat) removing the locked option when creating a supplier

### LINKED ISSUE #2012: (refactor) Remove the "locked" flag from the Supplier creation page
It doesn't make sense for a user to create a supplier that is automatically blocked.  This checkbox should be removed from the supplier creation page.  We do still need it on the update/edit page though.

### PR DESCRIPTION
**Pull request by jeremielodi**
closes #2012

### CODE REVIEW

**Comment by jniles** [comment]
@jeremielodi this looks perfect!

Unfortunately, this PR breaks our tests ... which us why we have tests!  The tests are found in the `test/end-to-end` folder.  They should be in a file called `suppliers.spec.js` or similar.  They check that there is an error message when a supplier is not locked - you should update these tests to remove any checks for `locked` field.

**Comment by jniles** [comment]
Aha, found it - [this line](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/test/end-to-end/suppliers/suppliers.spec.js#L78) will need to be removed.

**Comment by jniles** [comment]
Looks correct!

**Comment by jeremielodi** [comment]
Okay

**Pull request merged**
