### PR TITLE
feature(user): give ui-grid a loading indicator

### LINKED ISSUE #1357: (refactor) Put a loading indicator on the Users Module UI Grid
This `User` module does not have a loading indicator for it's UI-Grid.  On a slow connection, the grid looks broken.  We should put a loading indicator on to let the user know the state of the request.

### PR DESCRIPTION
**Pull request by jniles**
This commit puts a loading indicator on the users ui-grid so that the
page appears to perform responsively even on a high-latency network.

Closes #1357.

----
Thank you for contributing!

Before submitting this pull request, please verify that you have:
 - [x] Run your code through ESLint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
 - [x] Run integration tests.
 - [x] Run end-to-end tests.
 - [x] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

### CODE REVIEW

**Comment by sfount** [comment]
@jniles It looks like this fails on account management end to end tests, I'm not sure why this would be as this doesn't directly affect that but it seems to be reproducible.

**Comment by jniles** [comment]
Cheers, I'll check it out.

**Comment by jniles** [comment]
This is related to `bower.json` dependency issues.  I'll make an issue about it.  See #1423

**Comment by jniles** [comment]
See #1425.

**Pull request merged**
