### PR TITLE
feat(stock): adds link to stock lots

### LINKED ISSUE #4707: Link to the Lots in Stock from the Articles in Stock Registry
We still don't have a link that filters the "lots in stock" registry on an item from the "articles in stock" registry.  Let's add this link.  It would go here.

image

Basically, it would link the "lots in stock" filtered on the inventory item and depot from the "Articles in Stock" registry.

### PR DESCRIPTION
**Pull request by jniles**
Adds a link to the stock lots from the articles in stock registry.

Closes #4707.

image

### CODE REVIEW

**Comment by jeremielodi** [comment]
@jniles, why travis takes time to complete?

**Comment by jniles** [comment]
Good question.  It looks like it did complete successfully, but the webhook back to github clearly didn't fire:
https://travis-ci.com/github/IMA-WorldHealth/bhima/builds/175538638

I'll try to re-trigger the build.

**Comment by jniles** [comment]
It looks like I can't get GitHub to listen to Travis for this PR.  If you click on "details", you will see the PR has passed.  Can you go ahead and give a review anyway?  It shouldn't affect bors.

**Comment by jeremielodi** [comment]
bors try

**Review by jeremielodi — APPROVED** [review]

**Pull request closed without merging**
