### PR TITLE
feat(transaction edit) update grid height

### LINKED ISSUE #3535: Journal Edit Modal is too small for large transactions
Below, I have a transaction with ~51 lines in it, but I can only view a few at a time!  See below:
notenoughroomforlargetxns
_Fig 1: Only four lines displayed at a time in the Journal Edit Transaction Modal_

It would be nice to expand this to support many more lines so that we can easily make adjustments.

### PR DESCRIPTION
**Pull request by jeremielodi**
closes  #3535

### CODE REVIEW

**Comment by jeremielodi** [comment]
errors

**Comment by jeremielodi** [comment]
erro

**Review by jniles — APPROVED** [review]
LGTM.

bors r+

**Comment by jniles** [comment]
Looks like [this build](https://travis-ci.org/IMA-WorldHealth/bhima/jobs/484118596) is being hit by https://github.com/IMA-WorldHealth/bhima/issues/3529.  Would you be able to look into fixing that issue?

**Comment by jniles** [comment]
Let's see if the tests have been fixed.

bors r+

**Pull request merged**
