### PR TITLE
feat(Stock report) Movements dashboard

### LINKED ISSUE #4342: Create a Stock Movement Dashboard
Similar to https://github.com/IMA-WorldHealth/bhima/issues/4340, https://github.com/IMA-WorldHealth/bhima/issues/4339, and https://github.com/IMA-WorldHealth/bhima/issues/4341, we should implement a stock movement dashboard that groups stock movements by date over a period.  This would be accessible from the stock movement registry.  It would look something like this:

image
_Fig 1: Stock Movement Dashboard_

To configure this, a user needs to provide:
  1. The Fiscal Year
  2. The Period
  3. The Flux Type
  4. The type of data - # of movements or value of movements.

### PR DESCRIPTION
**Pull request by jeremielodi**
closes #4342

### CODE REVIEW

**Review by mbayopanda — COMMENTED** [review]
The chart working well 👍 

I have just noticed that : 

- The chart bars are too thin, is it possible to have more width for rectangles (bars) of the histogram 
image

Another observation is the fact that I think the report can be named `Stock Movement Chart` since a dashboard must include more than one synthesized information about stock movement

**Comment by jeremielodi** [comment]
Okay, let me see if I can improve it

**Comment by jeremielodi** [comment]
Je lis [https://www.chartjs.org/docs/latest/charts/bar.html](https://www.chartjs.org/docs/latest/charts/bar.html) où on montre comment ajuster ```barThickness```  mais le resultat n'est pas parfait

**Comment by jeremielodi** [comment]
chartjs a ses limites

**Comment by mbayopanda** [comment]
> Je lis [https://www.chartjs.org/docs/latest/charts/bar.html](url) où on montre comment ajuster `barThickness` mais le resultat n'est pas parfait

It seems like the page doesn't exist 😄

**Comment by jeremielodi** [comment]
<a href='https://www.chartjs.org/docs/latest/charts/bar.html'>cliquez ici alors</a>

**Comment by mbayopanda** [comment]
@jeremielodi could you update this work for being merged

**Review by mbayopanda — APPROVED** [review]
LGTM 👍 

bors r+

**Pull request merged**
