### PR TITLE
Feat(Stock exit)Remove Unit Price and Amount fields

### LINKED ISSUE #3950: Remove "Unit Price" and "Amount" fields from the Stock Exit UI and Receipt
I propose we remove the "unit price" and "amount" fields from the stock exit UI and receipt.  See the highlighted fields below:

image
_Fig 1: Stock Exit w/ Amount and Unit Price_

The reason for this is to avoid confusion.  The pharmacy should not be doing any accounting operations dealing with the value of the stock.  Instead, they should be dealing with the quantity in stock.

I think this will probably clear up a lot of confusion and facilitate stock operations.

### PR DESCRIPTION
**Pull request by jeremielodi**
closes #3950

### CODE REVIEW

**Comment by jniles** [comment]
bors try

**Review by mbayopanda — COMMENTED** [review]
Could you remove these columns also in the receipt generated

**Comment by jniles** [comment]
I'll pick this one up.

**Comment by jniles** [comment]
bors try

**Comment by jniles** [comment]
@mbayopanda this is ready for a second review.  Not sure why the CI isn't working on the pull request.

**Comment by jniles** [comment]
I'll go ahead and merge this in faith that it responds to @mbayopanda's reviews.  Code LGTM.

bors r+

**Pull request merged**
