### PR TITLE
Remove app state

### PR DESCRIPTION
**Pull request by lomamech**
- Delete all using of appstate

@jniles @sfount

### CODE REVIEW

**Comment by jniles** [comment]
Il n'y a pas quelque chose à  revoir dans le code.  LGTM.

@sfount, how does this fit in with the vision of 2.X?  Are these acceptable modules to delete at this time?

**Comment by jniles** [comment]
@lomamech, vous dites que vous aviez enlevé `appstate`, mais la service existe toujours.  Peux-tu enlevé cette service?

**Comment by lomamech** [comment]
Restore AppState services
because of application.js file located in the path clients/src/partials/bhima/ who uses the service AppState where the impossibility of removing this service

@jniles

**Comment by jniles** [comment]
LGTM.  Waiting for confirmation from @mbayopanda that e2e tests pass, then this will be merged.

**Pull request merged**
