### PR TITLE
make bhima MySQL8 compatible

### LINKED ISSUE #4463: Add official support for MySQL 8
Thanks to the work done by @individual-it, we know that MySQL 8 isn't supported by BHIMA.  In fact, only MySQL 5.7 is supported.  We've done the documentation updates to reflect this, but we should make the effort to target MySQL 8.  As pointed out by @individual-it in https://github.com/IMA-WorldHealth/bhima/issues/4393, Ubuntu 20.04 LTS ships with [MySQL 8 by default](https://www.digitalocean.com/community/tutorials/how-to-install-mysql-on-ubuntu-20-04#step-1-%E2%80%94-installing-mysql).

Let's put in first-class support for MySQL 8.  For now, the only things that have been established are that the `PASSWORD()` function has been removed.  It looks like we [can use a work-around](https://stackoverflow.com/a/60243956) while we set up a migration plan for our existing installations.  We'll just create the PASSWORD() function if it doesn't exist using the SO suggestions.

Once we have the workaround in place, we'll need to run the tests on MySQL 8 in a CI environment to ensure they continue working.

This issue will remain open until we've got the tests up and running.

### PR DESCRIPTION
**Pull request by individual-it**
by hacking a PASSWORD equivalent
fixes #4463

### CODE REVIEW

**Comment by jeremielodi** [comment]
You can create a function named ``` PASSWORD``` so that the query looks more readable.

Something like this :

```sql


CREATE FUNCTION `PASSWORD`(_pwd VARCHAR(40))
RETURNS VARCHAR(100) DETERMINISTIC
BEGIN
  RETURN CONCAT('*', UPPER(SHA1(UNHEX(SHA1(_pwd)))));
END
$$
```

**Comment by jeremielodi** [comment]
You can add your function at <a href='https://github.com/IMA-WorldHealth/bhima/blob/master/server/models/functions.sql'>function.sql</a>

**Comment by individual-it** [comment]
@jeremielodi that you for the suggestion, I'm just surprised that would work on 5.7 that already has this function
also when I try it manually I get 
```
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 4

**Comment by individual-it** [comment]
there seem also to be more issues beside password
```
  Fiscal Year

    ✓ blocks invalid form submission with relevant error classes (1614ms)

    ✓ creates a new fiscalYear (2189ms)

    ✓ edits a fiscal Year (1745ms)

    ✓ delete a fiscal Year (923ms)

  errors #interceptor() Error: ER_DATA_OUT_OF_RANGE: DECIMAL UNSIGNED value is out of range in '(`bhima_test`.`pt`.`debit` - `bhima_test`.`pt`.`credit`)'

  errors     at Query.Sequence._packetToError (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)

  errors     at Query.ErrorPacket (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)

  errors     at Protocol._parsePacket (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/Protocol.js:291:23)

  errors     at Parser._parsePacket (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/Parser.js:433:10)

  errors     at Parser.write (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/Parser.js:43:10)

  errors     at Protocol.write (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/Protocol.js:38:16)

  errors     at Socket.<anonymous> (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/Connection.js:88:28)

  errors     at Socket.<anonymous> (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/Connection.js:526:10)

  errors     at Socket.emit (events.js:310:20)

  errors     at addChunk (_stream_readable.js:286:12)

  errors     at readableAddChunk (_stream_readable.js:268:9)

  errors     at Socket.Readable.push (_stream_readable.js:209:10)

  errors     at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

  errors     --------------------

  errors     at Protocol._enqueue (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/Protocol.js:144:48)

  errors     at PoolConnection.query (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/Connection.js:198:25)

  errors     at /home/travis/build/IMA-WorldHealth/bhima/bin/server/lib/db/index.js:87:18

  errors     at Ping.onOperationComplete (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/Pool.js:110:5)

  errors     at Ping.<anonymous> (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/Connection.js:526:10)

  errors     at Ping._callback (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/Connection.js:488:16)

  errors     at Ping.Sequence.end (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)

  errors     at Ping.Sequence.OkPacket (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/sequences/Sequence.js:92:8)

  errors     at Protocol._parsePacket (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/Protocol.js:291:23)

  errors     at Parser._parsePacket (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/Parser.js:433:10)

  errors     at Parser.write (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/Parser.js:43:10)

  errors     at Protocol.write (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/protocol/Protocol.js:38:16)

  errors     at Socket.<anonymous> (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/Connection.js:88:28)

  errors     at Socket.<anonymous> (/home/travis/build/IMA-WorldHealth/bhima/node_modules/mysql/lib/Connection.js:526:10)

  errors     at Socket.emit (events.js:310:20)

  errors     at addChunk (_stream_readable.js:286:12) {

  errors   code: 'ER_DATA_OUT_OF_RANGE',

  errors   errno: 1690,

  errors   sqlMessage: "DECIMAL UNSIGNED value is out of range in '(`bhima_test`.`pt`.`debit` - `bhima_test`.`pt`.`credit`)'",

  errors   sqlState: '22003',

  errors   index: 0,

  errors   sql: 'SELECT a.id, a.number, a.label, a.type_id, a.label, a.parent, a.locked, a.hidden,\n' +

  errors     '      IFNULL(s.debit, 0) AS debit, IFNULL(s.credit, 0) AS credit, IFNULL(s.balance, 0) AS balance\n' +

  errors     '    FROM account AS a LEFT JOIN (\n' +

  errors     '      SELECT SUM(pt.debit) AS debit, SUM(pt.credit) AS credit, SUM(pt.debit - pt.credit) AS balance, pt.account_id\n' +

  errors     '      FROM period_total AS pt\n' +

  errors     '      JOIN period AS p ON p.id = pt.period_id\n' +

  errors     "      WHERE pt.fiscal_year_id = '1'\n" +

  errors     '        AND p.number = 0\n' +

  errors     '      GROUP BY pt.account_id\n' +

  errors     '    )s ON a.id = s.account_id\n' +

  errors     '    WHERE a.hidden = 0\n' +

  errors     '    ORDER BY CONVERT(a.number, CHAR(8)) ASC;'

  errors } +18s

    1) set the opening balance for the first fiscal year

**Comment by jeremielodi** [comment]
What if you change the function name to something like ```PASSWD```

**Comment by individual-it** [comment]
ok looks like the result when subtracting a UNSIGNED value from and other the result cannot be negative, except the `sql_mode = 'NO_UNSIGNED_SUBTRACTION';` is set 
https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_unsigned_subtraction

**Comment by individual-it** [comment]
now e2e tests fail with the known error 
image
see #4335

**Comment by individual-it** [comment]
@jeremielodi I've called the function `MYSQL5_PASSWORD`. What do you think?

**Comment by individual-it** [comment]
ToDo:
- [x]  comment in the functions sql file
- [x] run appvendor CI with MySQL8

**Comment by jeremielodi** [comment]
okay,  calling the function ```MYSQL5_PASSWORD``` sound like fine.

**Comment by individual-it** [comment]
now integration tests failing
image

**Comment by individual-it** [comment]
MySQL 8 seems to be more fussy when giving a string instead of a number, so this kind of requests return 400, what is correct. Sending a string for an ID is an invalid request

**Comment by kwilu** [comment]
Heads up @individual-it, we just merged some commits that conflict with the changes your made in this pull request! You can review this repository's [recent commits](https://github.com/IMA-WorldHealth/bhima/commits/master) to see where the conflicts occur. Please rebase your feature branch against the `upstream/master` branch and [resolve](https://zulip.readthedocs.io/en/latest/git/troubleshooting.html#recover-from-a-git-rebase-failure) your pull request's merge conflicts accordingly.

**Comment by jeremielodi** [comment]
What do you get when to try to parse the ```id``` like this

```js
const id = parseInt(req.params.id, 10);
```

**Comment by individual-it** [comment]
@jeremielodi for now I've adjusted the tests to send a valid id, but a not existing one. If we find a fix that works for both MySQL versions we can also add the old tests back, checking what happens if the id also has an invalid type.

But now I'm getting an error where I don't know how to progress
the test `POST /stock/lots/movements distribute lots to patients from a depot` breaks because the compared arrays are not the same. see https://ci.appveyor.com/project/jniles/bhima/builds/32786367/job/orni3ue7r432lr8p

looks like 
```agent.get(`/stock/lots/movements?document_uuid=${docUuid}`);``` and 
```agent.get(`/stock/lots/movements?reference=${firstMvt.documentReference}`);``` return different results

image

**Comment by jeremielodi** [comment]
@individual-it , I'm trying to settup a server on line where I will have mysql 8 installed then it will be easy for me to test together with you.

**Comment by jeremielodi** [comment]
It seems that your tests passe

**Comment by individual-it** [comment]
@jeremielodi how did you set up MySQL to make the test pass? They don't in CI https://ci.appveyor.com/project/jniles/bhima/builds/32786367/job/orni3ue7r432lr8p

**Comment by jeremielodi** [comment]
I did not change anything really. I had also your issue but when I restart the test it worked.
I'm investigating..

onlinetest

**Comment by jeremielodi** [comment]
I faced a problem with PDF tests and quickly solved it like this, I don't know if it's because I a got a Ubuntu 20 server.

diff

**Comment by jeremielodi** [comment]
It seems like puppeteer requires some extensions, that was the cause of the pdf tests errors on Ubuntu 20

 apt install libnss3-dev
 apt install libcups2-dev
 sudo apt-get install libxss1
 sudo apt-get install libgbm1
 sudo apt-get install libatk-bridge2.0-0
 sudo apt-get install -y libpangocairo-1.0-0
 sudo apt install libgtk-3-dev

**Comment by jeremielodi** [comment]
When I add ```only``` for checking only this test it seems to be okay.

```js

 // create stock movement to patient
  it.only('POST /stock/lots/movements distribute lots to patients from a depot', () => {

    let docUuid;
    let mvtsByDocument;
    let firstMvt;
    return agent.post('/stock/lots/movements')
      .send(shared.movementOutPatient)
      .then((res) => {
        helpers.api.created(res);
        // get details of the movement
        docUuid = res.body.uuid;
        return agent.get(`/stock/lots/movements?document_uuid=${docUuid}`);
      })
      .then((res) => {
        mvtsByDocument = res.body;
        [firstMvt] = mvtsByDocument;
        return agent.get(`/stock/lots/movements?reference=${firstMvt.documentReference}`);
      })
      .then(res => {
        /**
         * check if the result with document_uuid is the same with
         * the reference
         */
        expect(res.body).to.be.deep.equal(mvtsByDocument);
      })
      .catch(helpers.handler);
  });
```

skip

**Comment by jeremielodi** [comment]
Look at what I notice, the diffierence between uuids

log-error

**Comment by jeremielodi** [comment]
I have found where the problem is.
We are comparing two arrays having the same data but ordered differently.
```js

const a = [{
  uuid : '064AB1D952464402AE8A958FCDB07B35',
  label : 'VITAMINE-A',
  initial_quantity : 100,
  quantity : 10,
  reference : 8,
  description : 'Stock Exit to patient',
  depot_text : 'Depot Principal',
  io : 'OUT',
  unit_cost : 2,
  expiration_date : '2019-04-30T00:00:00.000Z',
  inventory_uuid : 'F6556E729D0547998CBD0A03B1810185',
  origin_uuid : 'E07CEADC82CF4AE2958A6F6A78C87588',
  entry_date : '2017-02-02T11:09:25.000Z',
  code : 'DINJ_TRIB1A2_0',
  text : 'Vitamines B1+B6+B12, 100+50+0.5mg/2ml, Amp, Unité',
  depot_uuid : 'F9CAEB16168443C5A6C447DBAC1DF296',
  is_exit : 1,
  date : '2020-05-11T22:16:34.000Z',
  document_uuid : 'FA428FB92A5F45A6948017ECA92E43FE',
  flux_id : 9,
  entity_uuid : '274C51AEEFCC423898C6F402BFB39866',
  flux_label : 'STOCK_FLUX.TO_PATIENT',
  delay : 1,
  invoice_uuid : null,
  invoice_reference : null,
  unit_type : 'unité',
  documentReference : 'SM.9.8',
},
{
  uuid : 'AE735E998FAF417BAA639B404FCA99AC',
  label : 'Lot Quinine Updated',
  initial_quantity : 100,
  quantity : 20,
  reference : 8,
  description : 'Stock Exit to patient',
  depot_text : 'Depot Principal',
  io : 'OUT',
  unit_cost : 1.5,
  expiration_date : '2020-12-15T00:00:00.000Z',
  inventory_uuid : '43F3DECBFCE9426E940ABC2150E62186',
  origin_uuid : 'E07CEADC82CF4AE2958A6F6A78C87588',
  entry_date : '2017-02-02T11:09:25.000Z',
  code : 'DORA_QUIN1S-_0',
  text :
    'Quinine Bichlorhydrate, sirop, 100mg base/5ml, 100ml, flacon, Unité',
  depot_uuid : 'F9CAEB16168443C5A6C447DBAC1DF296',
  is_exit : 1,
  date : '2020-05-11T22:16:34.000Z',
  document_uuid : 'FA428FB92A5F45A6948017ECA92E43FE',
  flux_id : 9,
  entity_uuid : '274C51AEEFCC423898C6F402BFB39866',
  flux_label : 'STOCK_FLUX.TO_PATIENT',
  delay : 1,
  invoice_uuid : null,
  invoice_reference : null,
  unit_type : 'unité',
  documentReference : 'SM.9.8',
}];
```

```js

const b = [{
  uuid : 'AE735E998FAF417BAA639B404FCA99AC',
  label : 'Lot Quinine Updated',
  initial_quantity : 100,
  quantity : 20,
  reference : 8,
  description : 'Stock Exit to patient',
  depot_text : 'Depot Principal',
  io : 'OUT',
  unit_cost : 1.5,
  expiration_date : '2020-12-15T00:00:00.000Z',
  inventory_uuid : '43F3DECBFCE9426E940ABC2150E62186',
  origin_uuid : 'E07CEADC82CF4AE2958A6F6A78C87588',
  entry_date : '2017-02-02T11:09:25.000Z',
  code : 'DORA_QUIN1S-_0',
  text :
    'Quinine Bichlorhydrate, sirop, 100mg base/5ml, 100ml, flacon, Unité',
  depot_uuid : 'F9CAEB16168443C5A6C447DBAC1DF296',
  is_exit : 1,
  date : '2020-05-11T22:16:34.000Z',
  document_uuid : 'FA428FB92A5F45A6948017ECA92E43FE',
  flux_id : 9,
  entity_uuid : '274C51AEEFCC423898C6F402BFB39866',
  flux_label : 'STOCK_FLUX.TO_PATIENT',
  delay : 1,
  invoice_uuid : null,
  invoice_reference : null,
  unit_type : 'unité',
  documentReference : 'SM.9.8',
},
{
  uuid : '064AB1D952464402AE8A958FCDB07B35',
  label : 'VITAMINE-A',
  initial_quantity : 100,
  quantity : 10,
  reference : 8,
  description : 'Stock Exit to patient',
  depot_text : 'Depot Principal',
  io : 'OUT',
  unit_cost : 2,
  expiration_date : '2019-04-30T00:00:00.000Z',
  inventory_uuid : 'F6556E729D0547998CBD0A03B1810185',
  origin_uuid : 'E07CEADC82CF4AE2958A6F6A78C87588',
  entry_date : '2017-02-02T11:09:25.000Z',
  code : 'DINJ_TRIB1A2_0',
  text : 'Vitamines B1+B6+B12, 100+50+0.5mg/2ml, Amp, Unité',
  depot_uuid : 'F9CAEB16168443C5A6C447DBAC1DF296',
  is_exit : 1,
  date : '2020-05-11T22:16:34.000Z',
  document_uuid : 'FA428FB92A5F45A6948017ECA92E43FE',
  flux_id : 9,
  entity_uuid : '274C51AEEFCC423898C6F402BFB39866',
  flux_label : 'STOCK_FLUX.TO_PATIENT',
  delay : 1,
  invoice_uuid : null,
  invoice_reference : null,
  unit_type : 'unité',
  documentReference : 'SM.9.8',
}];
```

**Comment by jeremielodi** [comment]
To solve this issue we have to add a default ```order by`` in  getLots function which is in <a href='https://github.com/IMA-WorldHealth/bhima/blob/master/server/controllers/stock/core.js'>here</a>

order

**Comment by jeremielodi** [comment]
To solve this issue we have to update the ```order by``` in  getLotsMovements function which is in <a href='https://github.com/IMA-WorldHealth/bhima/blob/master/server/controllers/stock/core.js'>here</a>

order


order2

**Comment by individual-it** [comment]
@jeremielodi thank you for the tip, the tests are green now!

The question is now how do you want the software to react when an invalid data-type is send to the API endpoint. For some requests there are checks like 
```      
if (!rows.length) {
        throw new NotFound(`
          Could not find a cash box account currency with id ${req.params.currencyId}.
        `);
      }
```
So if the DB returns no rows the client received a 404, MySQL 5.7 returns 0 rows when getting n invalid data-type but MySQL 8 throws an exception already when executing the query and the client receives a 400 Error.
We could:
1. adjust the tests to expect different results when running on different DB - would be strange to have the API react differently depending on the database
2. check the data-type before running the query and throw `BadRequest` if its wrong - that would emulate the MySQL 8 behaviour in MySQL 5.7
3. catch the exception of MySQL 8 and re-throw `NotFound` - that would keep the API behaviour as it is, currently

**Comment by jeremielodi** [comment]
Okay, today I will try to reproduce this issue on my server and see what way is the best to fix it

**Comment by jeremielodi** [comment]
This is my first test with mysql 8. I'm trying to see how mysql 8 react when  an  invalid data-type is passed as argument.

mysql8_queries

I'm working now with our API to see their behavior

**Comment by jeremielodi** [comment]
@individual-it  I don't think the  invalid data-type send to the API endpoint problem is general, here is what I have gotten as result when I try to use a string ```id``` instead of  int.

integration1

Here is what I changed
test001

**Comment by individual-it** [comment]
@jeremielodi yes the select works, but no updates/deletes. Can you try `DELETE FROM service WHERE id='str';`?

**Comment by individual-it** [comment]
ToDo:
- [ ]  400/404 response of MySQL 8/5.7 in case of update when the id is given as string (see above discussion)
- [ ]  fix documentation, see #4494

**Review by jeremielodi — APPROVED** [review]
Look good to me, great job @individual-it 
Thanks 👍

**Comment by individual-it** [comment]
@jeremielodi do you want already merge this? I did not understand what you want to do with the API calls that react now different in MySQL 8

**Comment by jeremielodi** [comment]
I was just trying to notice the bug you faced on API calls.

**Comment by jniles** [comment]
Awesome work @individual-it!  Thanks @jeremielodi.

I think the other two TODOs can be addressed in a subsequent PR as this one has been merged.  In truth, we don't expect to receive invalid IDs all that often, and most of the tests were pretty contrived to make obvious failure cases.  It would be good to define and document specific behaviors for these failure cases though.

**Comment by individual-it** [comment]
OK, I've created a new issue for the different API responses  #4501
just so, that its documented for now

**Pull request merged**
