### PR TITLE
Shipment updates

### LINKED ISSUE #6721: Update shipments timeline
The recently added "Delivered" to the state of shipments.  The timelines in the overview, etc, need to be updated to reflect that.

### LINKED ISSUE #6732: Add weight total and flexible per-item weight to shipments
When creating a new shipment, it is useful to include the weight of each item and the total weight of the shipment.  This is information that is needed when working with shipping companies.   

Proposed changes

- Add unit_weight to shipment_item.  This would default to the "weight" field in the corresponding inventory item.   But it could be edited during the construction of  shipment, if needed.
- Show the item weight (on each line) and the total cumulative weight for the shipment (at the bottom)
- Update the total weight as each item is added or quantities are updated.
- Print the weight info on the shipping document

### LINKED ISSUE #6734: Update Shipment document to be usable for actual shipping
The shipment "document" (available through the Shipments registry action menu) prints out a file that is similar to the shipments "overview" document.  I propose restructuring it to not include the timeline, include more of the information on who to deliver it to, etc.  This would be a document that could be sent with the shipment (or sent via PDF) to the receiving end, that would be more useful for the receivers.

### PR DESCRIPTION
**Pull request by jmcameron**
This PR updates several things with shipments.
- Adds per-item unit weight to shipping items (value defaults to the inventory unit_weight but  can be overridden)
- Updates to the Shipments "overview" timeline (still needs a bit more work)
- Converts the shipment document (via the shipment registry action menu) to a report usable during actual shipments. 
   - Adds several fields to shipments (transport_mode, receiver)
   - Based on feedback from projects
   - Removes old delivery timeline from this document
   - Sample version attached: [Sample-BHIMA-shipment-document.pdf](https://github.com/IMA-WorldHealth/bhima/files/9112546/Sample-BHIMA-shipment-document.pdf)

Closes https://github.com/IMA-WorldHealth/bhima/issues/6732
Closes https://github.com/IMA-WorldHealth/bhima/issues/6734
Closes https://github.com/IMA-WorldHealth/bhima/issues/6721

**TESTING**
- Create a shipment
   - Add notes
   - Add info on the receiver and transport mode
   - Save the shipment
- Edit origin depot and destination depots (under Stock > Depot management) to add address/contact info that will appear in the shipment TO/FROM boxes.
- To get the depot address automatically added to the shipment TO/FROM box, edit a depot and "Join a location" to it
- In the Shipment Registry, use the action menu for a shipment and choose the "Document" option to see the report

### CODE REVIEW

**Review by mbayopanda — COMMENTED** [review]
Thank you @jmcameron for this feature, here are some comments: 
- The total weight is not calculated 
image

- The unit column is empty 
 
- Some French translations are missing 

image

- The shipment receipt is 👍🏽  

- The total weight in the shipment receipt is not correctly calculated 

image

**Comment by jmcameron** [comment]
>     * The total weight is not calculated
>     * The unit column is empty
>     * Some French translations are missing
>     * The total weight in the shipment receipt is not correctly calculated

I think I've fixed these items.

**Comment by jmcameron** [comment]
Note that this update is a work in progress.  We will need to create 2 documents: (1) a document for internal use, and (2) a shipping manifest.   Currently the "document" (from the action menu) has a mix of these.  I'll add another issue to address this.

**Comment by mbayopanda** [comment]
LGTM 👍🏽 

bors r+

**Pull request merged**
