### PR TITLE
feat(transaction) improving transactions descriptions

### LINKED ISSUE #1930: (proposal) Include inventory item descriptions in transaction description lines
When researching transactions that are made against an individual account it is often useful to see what that line in the transaction originally referred to. If the line was for an invoice it may well be referencing an invoice item. 

I propose we update our invoice posting procedures to include the inventory item description in each line of the Transaction description.

### PR DESCRIPTION
**Pull request by jeremielodi**
This PR helps to Include the  inventory item descriptions in the transaction description 

closes #1930

### CODE REVIEW

**Comment by sfount** [comment]
@jeremielodi Can you reference the issue that this pull request solves? That would be useful for the reviewer

**Comment by jeremielodi** [comment]
closes #1930

**Comment by sfount** [comment]
To briefly add to the description of work: 

In the past financial transactions descriptions have been the same for every single line. With an invoice this means that the debt to the patient and the credit to all inventory items have the same description. 

The introduced functionality concatenates the invoice identifier (`IV.HSP.20`) with the inventory items description for each transaction line that directly references an invoice item.

**Current Functionality (Example)**

| ID | Account | Description | Debit | Credit | 
|---|---|---|---|---|
|HEV200|100|Invoice to Rosemary Stokes (PA.HSP.7) for 2 items from service Administration.|100|0|
|HEV200|500|Invoice to Rosemary Stokes (PA.HSP.7) for 2 items from service Administration.|0|20|
|HEV200|300|Invoice to Rosemary Stokes (PA.HSP.7) for 2 items from service Administration.|0|80|

**Introduced Functionality (Example)**

| ID | Account | Description | Debit | Credit | 
|---|---|---|---|---|
|HEV200|100|Invoice to Rosemary Stokes (PA.HSP.7) for 2 items from service Administration.|100|0|
|HEV200|500|IV.HSP.20: Quinine (100mg tablets).|0|20|
|HEV200|300|IV.HSP.20: Paracetamol tablets.|0|80|

**Review by jniles — APPROVED** [review]
Code LGTM.  I appreciate the extra description, very clear.  :+1:

When I get back to a computer I'll spin this up and try it out.  If it all works as expected, I'll give it a merge.

**Pull request merged**
