### PR TITLE
Add required inventory scan registry

### LINKED ISSUE #6466: Add support for required asset inventory scans
We would like the ability to require an inventory scan of a set of assets.  These could be ALL assets, or all the assets at a particular destination or depot, or all assets assigned to a particular entity.  Each required inventory scan would have a due date as well as information about the requestor, purpose, etc.   These inventory scans may be required on a  periodic basis or an arbitrary date.   Also, it seems possible that a specific asset may be need scanning for two different inventory scans at the same time.  Based on all that, it seems clear that we need the ability to define an "Asset Inventory Scan" with the following data:

Inventory Scan (SQL table)
 - Created date
 - Due date
 - Brief description
 - Depot (optional)
 - Inventory (optional)
 - Inventory Group (optional)
 - is_asset (1, 0, NULL)
 - Assigned to (optional)
 - Reference number (optional, this is the 'reference_number' used to refer to lots/assets being tracked by an organization providing them.

The goal of the "depot", "assigned_to", "inventory", "inventory_group", "is_asset", etc fields above is to allow a search all applicable assets (lots) to list the relevant lots (work like filters).  In conjunction with the asset_scans table, it should be straightforward to list all unscanned assets, etc, for more detailed reports.

Also need to add a page under "Assets Management" to support "Required Asset Inventory Scans".  Include creating new, editing old, and action menu items for getting status of scanned vs unscanned data, etc.  Also need regression tests.

### PR DESCRIPTION
**Pull request by jmcameron**
Implemented the "Required Inventory Scans" registry under the "Assets Management" menu folder
- Adds ability to created required inventory scans with due date.  Options support various types of scans (eg, for specific depots, assets only, etc).

**NOTES:** 
- Only creates the Required Inventory Scan items.   Using them for reports or listing assets needing scanning, etc will need to be done later.
- Note: Did not add support for inventory, inventory group, or is_assigned.  If we decide we need those later, we can add them.

Closes https://github.com/IMA-WorldHealth/bhima/issues/6466

**TESTING**
- Use bhima_test
- Go to Asset Management > Required Inventory Scans
  - Use [Add] button at the top to create a new required scan
  - Use the Action menu on the new item to edit the required scan.  Try editing all fields, saving, observing the display in the grid, etc.
   - Please check French translations for fixes/improvements
- Please also try this with a production site to make sure the migration scripts work.

### CODE REVIEW

**Review by mbayopanda — APPROVED** [review]
The code is looking good, my question is about the necessity of having `Required Inventory Scan items` we can figure out how to link `Required Inventory Scan` with `Asset Scanned`.

We can improve the `Asset Scan` with the reference of the `Required Inventory Scan` which will be helpful for reporting.

This PR is LGTM 👍🏽

**Comment by jmcameron** [comment]
@mbayopanda .  Thanks for the review.  Let me try to explain.  We could add a "Add New Required Inventory Scan" Button/menu item on the Asset Scans Registry page.  But let me ask you to think about this process:
- Someone wants to validate that the assets send to a certain destination site (Depot) are still being used.   So they create a "Required Inventory Scan" that sets a certain deadline for the assets there to be scanned.  Creating this "Required Inventory Scan" could be done in the registry (like I have it), or via a special [Add] button in the Asset Scans Registry.
- Later someone wants to track the progress of the people at the destination site in scanning the asssets.  How do they find the "Required Inventory Scans" object so that summary data or reports can be seen?   It is awkward finding it via the Asset Scans Registry page.  Much more direct to have a dedicated "Required Inventory Scans" registry to that summary data can be found via the action menu for the desired inventory scan. 
- Suppose you need to change the deadline for the scan?  How do you find it to edit it.  Again a dedicated registry seems appropriate.

**Comment by mbayopanda** [comment]
> @mbayopanda .  Thanks for the review.  Let me try to explain.  We could add a "Add New Required Inventory Scan" Button/menu item on the Asset Scans Registry page.  But let me ask you to think about this process:
> - Someone wants to validate that the assets send to a certain destination site (Depot) are still being used.   So they create a "Required Inventory Scan" that sets a certain deadline for the assets there to be scanned.  Creating this "Required Inventory Scan" could be done in the registry (like I have it), or via a special [Add] button in the Asset Scans Registry.
> - Later someone wants to track the progress of the people at the destination site in scanning the asssets.  How do they find the "Required Inventory Scans" object so that summary data or reports can be seen?   It is awkward finding it via the Asset Scans Registry page.  Much more direct to have a dedicated "Required Inventory Scans" registry to that summary data can be found via the action menu for the desired inventory scan. 
> - Suppose you need to change the deadline for the scan?  How do you find it to edit it.  Again a dedicated registry seems appropriate.
> 

I agree with the current state of having the Required Inventory Scans Registry, I would like to know where Required Inventory Scanned Items will be stored? In a new table or we will still use the existing table of Assets Scanned

**Review by lomamech — COMMENTED** [review]
I also have difficulties to understand the link between **Assets Scans Registry**
 and **Required Inventory Scans**
 
I also noticed that there is no search option by date
image

**Comment by lomamech** [comment]
image
I also noticed that the text overflows on the modal

**Comment by lomamech** [comment]
image
What is the meaning of No Asset, would it be **All inventories?**

**Comment by jmcameron** [comment]
> I also noticed that there is no search option by date

I agree this needs to be added.  I will add an issue so we can add this later.

**Comment by jmcameron** [comment]
This is ready for another review.  I updated the PR as follows:
- Fix the title on the edit modal (see [this comment](https://github.com/IMA-WorldHealth/bhima/pull/6477#issuecomment-1082149418)).
- Changed the logic of 'is_asset'.   (See [this comment](https://github.com/IMA-WorldHealth/bhima/pull/6477#issuecomment-1082151371)).  In general, we will be limiting inventory scans to assets.  So I made that a simple required boolean:  true => assets only.   false => all lots, not just assets.   Note that I also hid the 'is_asset' column in the Required Inventory Scans' registry since it will almost always be true (eg, assets only).   If we end up inventorying non-asset stock later, we may want to revisit this.
- I added a start day and changed "Due Date" to "End Date".   Note that the start date could be in the past.  Having a start date will be necessary since inventory scans require that the assets be scanned between certain dates.
- I will add an issue to add more search filters (see [this comment](https://github.com/IMA-WorldHealth/bhima/pull/6477#pullrequestreview-924967176)).

**Review by lomamech — APPROVED** [review]
image

Good

**Pull request merged**
