### PR TITLE
Integration of Review Recommandation

### PR DESCRIPTION
**Pull request by lomamech**
@DedrickEnc 
This is a new branch in which I took into account all recommendations that existed in the former branch

I kept using accountClean because many validation rules that exist in the interface of the Accounts module,

### CODE REVIEW

**Comment by lomamech** [comment]
@sfount 
I have met a lot of problems with my old local branch had become unitilisable, I close it and I send this new pull request with the same recommendation

**Comment by DedrickEnc** [comment]
@sfount
Can you start review this PR, I can do that if it is not possible
@lomamech has touched many files wich are not important for now such as `fiscal.js`, `creditor_goup` and many other. 
Those files can be ignored but I don't know, what is the best way between deleting them, creating an other folder for unused files and ignoring them

**Comment by DedrickEnc** [comment]
@IMA-WorldHealth/local-contributors 
It should be good to touch only files which are integrated to bhima-2.X and not other.

**Comment by lomamech** [comment]
Ces fichiers on était modifier suite aux diverses modifications concernant
- La suppression de la propriété is_used_budget)
- L'utilisation de type_id aulieu de account_type_id
- L'utilisation de number aulieu de account_number
- L'utilisation de label aulieu de account_txt

2016-03-21 15:00 GMT+01:00 Dedrick Kitamuka notifications@github.com:

**Comment by sfount** [comment]
@lomamech Thanks for this. @DedrickEnc @lomamech I will be catching up reviewing actions from the last 2 weeks today and tomorrow - I will get to this pull request as soon as possible. 154 files is a lot! 

The review process will happen all at once, I would like to discourage working on fixes at exactly the same time they are reviewed. Thanks!

**Comment by DedrickEnc** [comment]
> Ces fichiers on était modifier suite aux diverses modifications concernant
> - La suppression de la propriété is_used_budget)
> - L'utilisation de type_id aulieu de account_type_id
> - L'utilisation de number aulieu de account_number
> - L'utilisation de label aulieu de account_txt

@lomamech 
Je comprend ce que tu dis, sauf que dans le proget bhima-2.X la plus part de ce fichier sont desactivEs alors c'est pour ca que je disais ca ne valait peut etre pas la peine de les toucher.
Je laisse le soin a @sfount  de decider ce qu'il compte faire de ca.

**Comment by sfount** [comment]
@lomamech I think it would be best to delete _all_ files that are not yet part of bhima-2.x. I have reviewed most of the files I think are new but I will do a final review once those files have been deleted. 

(Deleted files can be recovered in the future if people need to use them).

**Comment by lomamech** [comment]
- Delete unused files
- Improve unit Account
  @sfount

**Comment by sfount** [comment]
@IMA-WorldHealth/local-contributors This commit https://github.com/IMA-WorldHealth/bhima-2.X/pull/201/commits/45584ce0cbcac79283ddf006fbe0689ab01f8d26 is a perfect example of what excellent (maintainable) development looks like. 

Many of these things I still forget to do however as we iterate as a team we will find ourselves mastering them:
- Commit message describes _exactly_ what the commit does

> Add ng-messages
> Changing the submit function to send forms
> throw new NOT_FOUND () for server error handing
- Re-factoring recently written code with the latest standards; each change here improves on a pattern that makes code more readable or less difficult to maintain (ng-messages will stay up to date with changes to the directive)
- Every integration test passes (final commit in pull request) 
- Every end to end test passes with the re-factor made (final commit in pull request)

@lomamech :+1:

**Pull request merged**
