### PR TITLE
fix(stock): submit button active only when valid on exit

### PR DESCRIPTION
**Pull request by jniles**
This commit ensures the submit button on the exit module is only active
when the form is valid for submission.  Previously, there was a corner
case where we would enable the submit button after a date change,
despite not having valid data.

Partially addresses #5425.

### CODE REVIEW

**Review by jmcameron — COMMENTED** [review]
The code looks good.
I tested this and it seems to work.

I was confused about one thing:  When you change the date to one before the present or in the future, it deletes ALL the current inventory items.  I found this strange.  It probably should give you a warning that you'll need to reselect the inventory items.  This could be improving the current "you have chosen a past date" message to indicate that has deleted any inventory items and you need to reselect them -- or, when you click on the [Change Date] button, it could pop up a dialog that confirms that you'll need to reselect the inventory items.

**Comment by lomamech** [comment]
@jniles  it's really curious I can't reproduce this error

**Review by lomamech — APPROVED** [review]
Although I did not manage to reproduce this error, the changes made will prevent the submit button from remaining usable when the grid is empty

**Pull request merged**
