### PR TITLE
Stay on posting journal page after posting data on ledger

### LINKED ISSUE #1222: (proposal) Do not navigate to GL after posting
Traditionally, we have navigated the user to the GL after completing the posting process.  The original design for the Trial Balance (https://github.com/IMA-WorldHealth/bhima-2.X/issues/585) called for the option to link to the GL, but not an immediate transition.

I propose we eliminate the transition altogether, instead offering the user the possibility to close the Trial Balance modal once the transactions are posted.  This will encourage our users to look at small groups of transactions at a time, posting in smaller number and verifying each one.

### PR DESCRIPTION
**Pull request by lomamech**
Stay on posting journal page after posting data on ledger

closes #1222

### CODE REVIEW

**Review by jniles — APPROVED** [review]
LGTM

**Comment by jniles** [comment]
@kwilu r+

**Comment by ghost** [comment]
:pushpin: Commit 14dbff5 has been approved by `jniles`

**Comment by ghost** [comment]
:hourglass: Testing commit 14dbff529c43b3bbe463bb696afaafb1724734a5 with merge 4edc0548ae0b950394bb76f8c34bd2e160159a47...

**Pull request merged**
