### PR TITLE
improve(Employee Standing)

### LINKED ISSUE #3778: Improving the employee's financial status report
Improving the employee's financial status report, making the join of the medical care part brought to the employee optional

### PR DESCRIPTION
**Pull request by lomamech**
- Adding option to include medical care provided to the employee
- Update Report, display Employee Standing Status in Report

closes #3778

### CODE REVIEW

**Comment by kwilu** [comment]
Hello @lomamech, it seems like you have referenced #3778 in your pull request description, but you have not referenced them in your commit message description(s). When you reference an issue in a commit message, it automatically closes the corresponding issue when the commit is merged.

Please run `git commit --amend` in your command line client to amend your commit message description with `Fixes #3778.`.

An example of a correctly-formatted commit:
```
commit fabd5e450374c8dde65ec35f02140383940fe146
Author: kwilu
Date:   Sat Mar 18 13:42:40 2017 -0700

    pull requests: Check PR commits reference when issue is referenced.

    Fixes #51.
```

Thank you for your contributions to BHIMA!

**Comment by lomamech** [comment]
image

**Comment by lomamech** [comment]
image
The employee's financial situation and the total care provided to the employee

**Comment by lomamech** [comment]
image

**Comment by lomamech** [comment]
@jniles can you review this PR

**Review by jniles — APPROVED** [review]
@lomamech, looks good to me.  Well done.

bors r+

**Pull request merged**
