### PR TITLE
chore(units): merge accounting + finance

### LINKED ISSUE #479: Merge Finance and Accounting concepts
Currently our tree has two categories for `Finance` and `Accounting`. I suggest that both of these are incorperated into `Finance`. The users and permissions set up will still allow us to give accountants access to accounting modules and other employees access to the input modules (invoices etc.). 

This would allow us to standardise the route structure as follows:

``` js
// A list of all of the patients in the hospital (Patient Registry)
'hospital/patients'

// A list of all of accounts for the institution (Account Management) 
'finance/accounts'
```

@IMA-WorldHealth/local-contributors

### PR DESCRIPTION
**Pull request by jniles**
This commit merges the accounting and finance concepts in bhima.  All financial and accounting modules are located under the tree node "Finance" as requested by #479.

Closes #479.

---

Thank you for contributing!

Before submitting this pull request, please verify that you have:
- [x] Run your code through JSHint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
- [x] Run integration tests.
- [x] Run end-to-end tests.
- [x] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

### CODE REVIEW

**Comment by sfount** [comment]
Excellent! This will help reduce the number of options until we have very clearly defined what module fits into what category (if it becomes appropriate).

Would you be able to include the module `headercrumb(tm)`s too?

``` bash
./partials/section_resultat/section_resultat.html
./partials/fiscal/fiscal.html
./partials/accounts/accounts.html
./partials/section_bilan/section_bilan.html
./partials/references/groups/groups.html
./partials/references/references.html
```

I know a number of these modules are not 2.x designed so they are not priority.

**Comment by jniles** [comment]
@sfount, sure no problem.  Didn't realize these values were actually shown to the client there!

**Comment by jniles** [comment]
@sfount, updated with suggestions.

**Comment by sfount** [comment]
LGTM 👍

**Pull request merged**
