### PR TITLE
chore(locations): add loading buttons

### PR DESCRIPTION
**Pull request by jniles**
The locations management section needs a lot of cleanup, but this will at least get us started by making sure double clicks don't result in duplicate records.

### CODE REVIEW

**Review by jeremielodi — COMMENTED** [review]
The code look perfet, there is one problem you can try to solve
When registering a new location, the componet should reload informations to help the user continue his process.

**Comment by jniles** [comment]
@jeremielodi, thanks for the review!  I'll make the changes and ping you back.

**Comment by jniles** [comment]
@jeremielodi, this is ready for a second review.

**Review by jeremielodi — COMMENTED** [review]
LGTM, well done!

**Pull request merged**
