### PR TITLE
feat(stock): allow mvnts filtering on invoice_uuid

### LINKED ISSUE #4099: Add links from invoice registry to the stock movements registry
We should add links similar to https://github.com/IMA-WorldHealth/bhima/issues/4098 and https://github.com/IMA-WorldHealth/bhima/pull/4087 to allow users to quickly jump from the invoice page to the stock movements registry to figure out if there was a distribution against a particular invoice.

### PR DESCRIPTION
**Pull request by jniles**
Adds in the ability to filter stock movements on invoice_uuid by linking
from the invoice registry.

Closes #4099.

### CODE REVIEW

**Review by mbayopanda — APPROVED** [review]
LGTM 👍 

bors r+

**Comment by jniles** [comment]
Why r-?

**Comment by mbayopanda** [comment]
@jniles Travis didn't validate the work yet :-)

**Comment by mbayopanda** [comment]
bors try

**Comment by jniles** [comment]
bors try

**Comment by mbayopanda** [comment]
bors try

**Comment by jniles** [comment]
bors try

**Pull request merged**
