### PR TITLE
feat(stock): link invoice from movements registry

### LINKED ISSUE #4377: Link the invoice from the stock
Just like we link the patient from the stock movement (if it exists), it would be nice to link the invoice.  It would appear in the dropdown, here:

image

### PR DESCRIPTION
**Pull request by jniles**
Adds a link to the invoice if it exists in the stock movement registry.

Closes #4377.

### CODE REVIEW

**Comment by jniles** [comment]
@jeremielodi can I get a review?

**Comment by jeremielodi** [comment]
@jniles can you please reproduce the senario where the link you added is displayed?, you can you shareX for that.
I wan to do the same thing in my computer and make sure that the link works as expected.

**Comment by jniles** [comment]
@jeremielodi sure.  It's when you distribute stock to a patient, you can optionally link their invoice.  Here is an example:

4WoIN8j1Qa

**Review by jeremielodi — APPROVED** [review]
LGTM 👍

**Pull request merged**
