### PR TITLE
Feature depot management assignation depot

### LINKED ISSUE #7091: Improved Depot Management assignation of depot
The BHIMA system can assign depots to a user for management and supervision. However, when a new deposit is added, it is assigned to users on a rotational basis. To improve deposit management, we suggest adding a new feature to the depot management interface that allows for specific user assignment. This feature will also allow for a comprehensive view of all users with access rights to a depot.

### PR DESCRIPTION
**Pull request by lomamech**
- Added the ability to assign management as well as supervision and management to users directly via the repository management interface
closes #7091

- Implement Integration test for depot and user for management and
  assignation

### CODE REVIEW

**Comment by lomamech** [comment]
**Assignments and Supervisions**
**_I. Problem_**

In the context of the SEMI project, we proceeded to the creation of individual repositories for each central office and each care structure. To date, we have configured over 500 repositories.

The user management module offers the possibility of configuring, for each user, the repositories to which he has management rights, as well as those to which he has supervision rights.

However, when a new repository is added, the difficulty lies in setting up users for management and supervision. In this context, it is necessary to assign several users, which implies doing it from the user management interface and repeating this same operation for each user.

**_II. Presentation_**

This feature is only available to users with access rights to the role configuration option.
In order to configure the users for the management or the supervision of a deposit, it is necessary to go to the register of deposits.

image


The repository management register contains the list of repositories as well as the users having management rights on each repository. On the far right is the “Actions” button which displays a list of options for performing different actions on a deposit.

image

Here we find the two new features which are:
- Add manager
- Add supervisor

**_II.1. Add a manager_**
When you select the "Add a manager" option, a modal window opens, displaying the name of the depot as well as the list of users with management rights for this depot (stock entry, stock exit and supervision).

image

Users configured for repository management can also be viewed through this module. To add or remove the right of use as a manager, simply check or uncheck the box in front of their name.

**_II.2. Add a supervisor_**
The "Add supervisor" option works the same way as that of the managers, with the exception that the supervisor is only authorized to consult the various registers and reports, without the possibility of inventory management for the deposit. On the other hand, the stock managers of the distribution center will have the right to manage the warehouse of the Central, while ensuring the supervision of stocks for all the central offices and care establishments.

image

**Review by jmcameron — COMMENTED** [review]
Good job!   The code looks good.   I tested this with bhima_test and the functions add depot managers and supervisors work very well.

I would like to see an additional column for the Supervisor in the Depot Management page.  This column could be optional (by adding column management).  This will be helpful since currently there is no way to see who is assigned as a supervisor without using the "Add Supervisor" function.

I was glad to see tests for the new functions for getting and setting depot managers and supervisors.    And the tests worked for me ('yarn test').

Another thing I was unclear about is how the limitations on supervisors are actually implemented in regular depot operations.   In the PR description, I see "the supervisor is only authorized to consult the various registers and reports, without the possibility of inventory management for the deposit".   How is this enforced?   Perhaps I missed this when I was looking through the code changes.   I would like to see a description of how to verify this using the GUI as well as having tests for it.

**Comment by lomamech** [comment]
> Good job! The code looks good. I tested this with bhima_test and the functions add depot managers and supervisors work very well.
> 
> I would like to see an additional column for the Supervisor in the Depot Management page. This column could be optional (by adding column management). This will be helpful since currently there is no way to see who is assigned as a supervisor without using the "Add Supervisor" function.
> 
> I was glad to see tests for the new functions for getting and setting depot managers and supervisors. And the tests worked for me ('yarn test').
> 
> Another thing I was unclear about is how the limitations on supervisors are actually implemented in regular depot operations. In the PR description, I see "the supervisor is only authorized to consult the various registers and reports, without the possibility of inventory management for the deposit". How is this enforced? Perhaps I missed this when I was looking through the code changes. I would like to see a description of how to verify this using the GUI as well as having tests for it.

The addition of the deposit monitoring option was implemented at the beginning of this year, here are the references the references Issues and Pull Request:
https://github.com/IMA-WorldHealth/bhima/issues/6877
https://github.com/IMA-WorldHealth/bhima/pull/6901

**Comment by lomamech** [comment]
image
The supervisor column has been added

**Review by jmcameron — APPROVED** [review]
Thanks.  The changes work well.

**Pull request merged**
