### PR TITLE
feat(service) add hidden column

### LINKED ISSUE #3707: Add option to hide a service
The services module has many uses, but once someone makes a mistake, it is hard to correct.  We should add an option to allow users to "hide" services, so that further mistakes cannot be made.  This would mirror the hidden accounts option (#2808) and the services would be no longer available in the dropdown for invoicing.

image
_Fig 1: No options besides editing the service name_

**Design**
We need to add an additional boolean column to the service table `hidden`.  This will work exactly the same way the account `hidden` column works.   By default, the value is `0`, but it can be toggled via the web interface. 

The `bhServiceSelect` also needs to be modified to only look for non-hidden services by default (`?hidden=0`).

### PR DESCRIPTION
**Pull request by jeremielodi**
closes #3707

### CODE REVIEW

**Comment by kwilu** [comment]
Hello @jeremielodi, it seems like you have referenced #3707 in your pull request description, but you have not referenced them in your commit message description(s). When you reference an issue in a commit message, it automatically closes the corresponding issue when the commit is merged.

Please run `git commit --amend` in your command line client to amend your commit message description with `Fixes #3707.`.

An example of a correctly-formatted commit:
```
commit fabd5e450374c8dde65ec35f02140383940fe146
Author: kwilu
Date:   Sat Mar 18 13:42:40 2017 -0700

    pull requests: Check PR commits reference when issue is referenced.

    Fixes #51.
```

Thank you for your contributions to BHIMA!

**Comment by kwilu** [comment]
Hello @jeremielodi, it seems like you have referenced #3707 in your pull request description, but you have not referenced them in your commit message description(s). When you reference an issue in a commit message, it automatically closes the corresponding issue when the commit is merged.

Please run `git commit --amend` in your command line client to amend your commit message description with `Fixes #3707.`.

An example of a correctly-formatted commit:
```
commit fabd5e450374c8dde65ec35f02140383940fe146
Author: kwilu
Date:   Sat Mar 18 13:42:40 2017 -0700

    pull requests: Check PR commits reference when issue is referenced.

    Fixes #51.
```

Thank you for your contributions to BHIMA!

**Comment by kwilu** [comment]
Hello @jeremielodi, it seems like you have referenced #3707 in your pull request description, but you have not referenced them in your commit message description(s). When you reference an issue in a commit message, it automatically closes the corresponding issue when the commit is merged.

Please run `git commit --amend` in your command line client to amend your commit message description with `Fixes #3707.`.

An example of a correctly-formatted commit:
```
commit fabd5e450374c8dde65ec35f02140383940fe146
Author: kwilu
Date:   Sat Mar 18 13:42:40 2017 -0700

    pull requests: Check PR commits reference when issue is referenced.

    Fixes #51.
```

Thank you for your contributions to BHIMA!

**Review by jniles — APPROVED** [review]
This all looks great so far!

Could you write an integration test for updating the column?

**Comment by kwilu** [comment]
Hello @jeremielodi, it seems like you have referenced #3707 in your pull request description, but you have not referenced them in your commit message description(s). When you reference an issue in a commit message, it automatically closes the corresponding issue when the commit is merged.

Please run `git commit --amend` in your command line client to amend your commit message description with `Fixes #3707.`.

An example of a correctly-formatted commit:
```
commit fabd5e450374c8dde65ec35f02140383940fe146
Author: kwilu
Date:   Sat Mar 18 13:42:40 2017 -0700

    pull requests: Check PR commits reference when issue is referenced.

    Fixes #51.
```

Thank you for your contributions to BHIMA!

**Review by jniles — APPROVED** [review]
Code looks correct.  Great work.

bors r+

**Comment by jniles** [comment]
@jeremielodi can you fix conflicts in this to get it merged?

**Comment by kwilu** [comment]
Hello @jeremielodi, it seems like you have referenced #3707 in your pull request description, but you have not referenced them in your commit message description(s). When you reference an issue in a commit message, it automatically closes the corresponding issue when the commit is merged.

Please run `git commit --amend` in your command line client to amend your commit message description with `Fixes #3707.`.

An example of a correctly-formatted commit:
```
commit fabd5e450374c8dde65ec35f02140383940fe146
Author: kwilu
Date:   Sat Mar 18 13:42:40 2017 -0700

    pull requests: Check PR commits reference when issue is referenced.

    Fixes #51.
```

Thank you for your contributions to BHIMA!

**Pull request merged**
