### PR TITLE
Update license, dependencies, and environmental variable loading

### LINKED ISSUE #4: Use dotenv to manage configurations
The npm [dotenv](https://www.npmjs.com/package/dotenv) module would help us manage production/development/testing environments much more clearly and efficiently than our current JSON setup.  It would also give us a clear way to add new environmental variables (such as database configuration parameters, timers, etc) in the future.

For bhima, the basic idea would be to define an `.env` file (and `.env.example` for reference) that would _not_ be synced to Github.  It would have keys such as `PORT`, `DB_PASS`, `DB_USER`, `DB_HOST`, `EMAIL_FREQUENCY`, `LOG_LEVEL` etc, that are currently stored in `/server/environment/config`.  The dotenv module would allow the server to load these configuration properties once to be shared with all child modules, rather than passing around a JSON object from module to module.

### LINKED ISSUE #15: Use gulp-cssnano instead of gulp-minify-css
According to the [gulp-minify-css](https://www.npmjs.com/package/gulp-minify-css) page, the plugin is deprecated and should be swapped out for css-nano.

### PR DESCRIPTION
**Pull request by jniles**
This commit updates bhima's license to an SPDX valid license identifier (we are still GPL version 2).  It also updates the outdated dependencies in the package.json.  In particular, we no longer use the deprecated `gulp-minify-css` and instead use `gulp-cssnano`.  See [this page](https://www.npmjs.com/package/gulp-minify-css).  Closes #15.

**Breaking Change** This PR depends on the [dotenv](https://www.npmjs.com/package/dotenv) npm package to manage environmental variables.  You must have a `.env.production` file in the top level folder of the repository to run the application using `npm run app`.  To run tests, you must have a `.env.development` file.  Closes #4.

### CODE REVIEW

**Comment by jniles** [comment]
@sfount can you do a test of this branch before a merge to master?

**Comment by sfount** [comment]
@jniles - missed this message :-1:, will have it in this morning.

**Comment by jniles** [comment]
:+1:

**Comment by sfount** [comment]
Everything looks good; I think ensuring the default environment variables are configured would be a good next step for some build/ install script (for the future). 

Before this can be pulled all references to `server/config/environment/*` will need to be removed. Deleting the bin folder reveals these dependencies. 
I suggest:
- Including the `server-clean` gulp build process in the the `gulp build` command (ensuring the bin file is removed for every test) 
- Updating all references to the old configuration files. 

Cheers.

**Comment by jniles** [comment]
For reference (@IMA-WorldHealth/local-contributors),  `.env.production` and `.env.development` have now been uploaded to the `developers@imaworldhealth.org` google drive account.

**EDIT** also, thanks @sfount for the review.  Will get these changes in soon.

**Comment by jniles** [comment]
@sfount, the fixes you requested have landed in this branch.  Thanks!

**Pull request merged**
