### PR TITLE
Add budget module

### LINKED ISSUE #267: (Design) Budgets
This issue describes a design for the budgeting utility. 
`Finance / Budget`

The design focuses on creating reliable well tested tools that can be applied to many different situations and are not tied to one operation (creating an explosion of modules as we have seen before). 

Budget module

**Key points**
- Module consists of one large UI-Grid that shows all accounts in a tree structure 
- By the time the module has loaded the fiscal year that the user is budgeting for has already been selected (in this case Fiscal Year 2016) - this is demonstrated with a label as shown described here https://github.com/IMA-WorldHealth/bhima-2.X/issues/263
- The first two columns, `account` and `Annual Total` are pinned to the left, the other columns can overflow-x : auto;
- `split` allows the accountant to enter a value into the total and have that split (shared) amongst each of the periods, this should come with a warning if any of the periods have non-zero values
- Total row along the bottom shows this years entire budget
- Cells can be edited in each of the period columns automatically updated the annual amount for that line (and subsequently the total for the year)

Budget export CSV

**Export to CSV**
A major benefit of the structure proposed in https://github.com/IMA-WorldHealth/bhima-2.X/issues/257 is the ability to request the same data with multiple different 'renderers'. In this case the `json` renderer would be used to initially populate the UI grid. Selecting `export` -> `csv` would request **exactly the same data, from the same route** but passed through a `csv` renderer. 

Budget export PDF

**Export to PDF**
PDF budget report would be in lined just like receipts. This would allow it to be previewed, downloaded and printed. 

Any discussions relevant to the Budget module can be added to this thread! Once we have reviewed this process it can be assigned and a module proposal issue can be created to track progress. [(2.x development process)](https://docs.google.com/document/d/1Opak2BgrhXte0DzbKPmziY-aL7jIBj4PCnYhALmiy4w/pub)

### LINKED ISSUE #2807: Budget vs Balance Report
An important report for managers and financial analysts is the budget versus balance report.  Note that the report depends upon the implementation of #267.

### Budget versus Balance
The budget versus balance report is very similar to the Profit and Loss Statement.  It concerns only income and expense accounts.  The idea is to compare the income and expense accounts against what the budget has for the income and expense accounts.  Importantly, the report should show the variance between what has been budgeted and what was actually received.

### LINKED ISSUE #7086: Implementation of modules for budget management
Allow users to create and manage budgets
Provide an overview of budgets and expenses
Features:

- Creation of budgets with categories and sub-categories of expenses
- Adding and modifying transactions for each budget
- Generation of budget reports for in-depth analysis

Here is the original design document from 2015:
- [BudgetDesignProposal - Cameron - 2015-01-16.pdf](https://github.com/IMA-WorldHealth/bhima/files/12437895/BudgetDesignProposal.-.Cameron.-.2015-01-16.pdf)

Note that you can request an example Budget from @jmcameron.

### PR DESCRIPTION
**Pull request by jmcameron**
This PR adds a new module under the Finance menu for defining and tracking a budget.

Closes https://github.com/IMA-WorldHealth/bhima/issues/7086
Closes https://github.com/IMA-WorldHealth/bhima/issues/2807
Closes https://github.com/IMA-WorldHealth/bhima/issues/267  

Note that I had not seen Issue https://github.com/IMA-WorldHealth/bhima/issues/267 before today, but I think the new budget module implements most of what the issue describes.

*Preliliminary Documention*
- [BHIMA Budget Module (English) v5.pdf](https://github.com/IMA-WorldHealth/bhima/files/13442234/BHIMA.Budget.Module.English.v5.pdf)
- [Module Budgétaire BHIMA (French) v5.pdf](https://github.com/IMA-WorldHealth/bhima/files/13442247/Module.Budgetaire.BHIMA.French.v5.pdf)  Thanks for @Ebed-meleck for editing the French version!

**TESTING**

Here is how to test the basics of the budget module:
- Use bhima_test 
- Run `npm run build:db' to update the database_
- There is very little "Actuals" data in the test database, so do the next step to provide a little data
- Go to the `Finance > Journal`.  Select all transactions.   Click on the [Trial Balance] button on the toolbar and click on the [Submit] button in the Trial Balance dialog.
- Go to the `Administration > Role Management` page and edit your user permissions to allow the user to access the `Finance > Budget Management` page.
- Go to the `Finance > Budget Management` page.  You should see a display of the accounts with the budget and actuals data for the fiscal year.  
- Note that you can select a different fiscal year at the bottom of the page.
- In the [Menu] drop-down, select the 'Export YTD Budget Data (CSV)' option.  After the file has been created, edit the Budget column on any of the accounts you wish.  Note that there are only a couple of accounts that have actuals data.
- Go back to the BHIMA budget page.  In the [Menu], click on the 'Import Budget CSV file" option.
- You should see the display with added budget data.
- You can use the [Menu] to export a report with the current status
- You should also run the tests (`npm run test`) to verify that the basic tests work (which includes several tests related to the budget module.

### CODE REVIEW

**Review by mbayopanda — COMMENTED** [review]
That's awesome,

I have seen this typo:
image

The feature is working and the code is LGTM 👍🏽

**Comment by jmcameron** [comment]
> I have seen this typo: image
> 
> The feature is working and the code is LGTM 👍🏽

I pushed a fix for this typo.

**Comment by jmcameron** [comment]
Fixed another minor issue and updated to changes in Master, rebased.

**Comment by jmcameron** [comment]
Minor translation improvement.  Changed all percent deviations to be 100*actuals/budget; according to Chris, this is the way that folks here think about deviations.  Rebased.

**Comment by jmcameron** [comment]
Based on demonstrations to several people and discussions with other developers.  This ready to merge.

**Pull request merged**
