### PR TITLE
feat: automated backups w/ AWS S3

### LINKED ISSUE #2284: Investigate Amazon S3 for Backups
In previous version of BHIMA, we've used Dropbox to store data and backups.  Unfortunately, our backups have gotten large enough that we really need a more robust solution, preferably one that we can control fine-grained permissions settings on.  Additionally, we have instituted hacks on Dropbox's linux client to schedule uploads during certain intervals of time.

Since we will need to jump off a free tier at some point, I propose we use Amazon's [Simple Storage Service (S3)](https://aws.amazon.com/s3/).  There is a well developed [node module](https://www.npmjs.com/package/s3) for it.  The advantages are I see are:
 1. Very cheap - you pay month and access, often just cents (see the [pricing page](https://aws.amazon.com/s3/pricing/)).  Additionally, their [pricing calculator](http://calculator.s3.amazonaws.com/index.html) estimates that if we store ~25 GB, and make 1000 requests a month (both of these are overestimates), we will still pay less than $1/month.
 2. Access can be granted to specific individuals using Amazon's access control.
 3. Amazon S3 is a giant corporation serving many clients.  They do have downtime ... but will likely be more stable and responsive than smaller services.

@IMA-WorldHealth/bhima-core what do you think?

### PR DESCRIPTION
**Pull request by jniles**
This commit adds automated backups using Amazon's S3 data storage as the
online component.  Backups consist of three separate components:
 1) A mysqldump command to dump the data.
 2) A compression step to deflate data size
 3) An upload step to perform online backups.

The lib/backups.js library encapsulates all three steps in promises,
taking in the filename string at each step.  It has some debug() calls
scattered around to allow DEBUG=backups to show the internal workings of
the script.

Closes #2284.

backupamazons3
_Fig 1: What a backup looks like uploaded to AWS_

### CODE REVIEW

**Comment by jniles** [comment]
Note that this requires an S3 Access Key.  We'll have to figure out how to share it around for testing and deployment.

**Comment by jniles** [comment]
It looks like the s3 client is old and unmaintained.  There are a few issues related to the security vulnerability reported by snyk, see https://github.com/andrewrk/node-s3-client/issues/194 for the most recent one.

Fortunately, it looks like there is a fork that fixes the security issue https://github.com/andrewrk/node-s3-client/issues/190#issuecomment-339972395

I'll switch over the dependency to this fork in a second.

**Comment by jniles** [comment]
Switched.  Everything is green now 👍

**Review by mbayopanda — APPROVED** [review]
LGTM

**Comment by jniles** [comment]
Weeee!

bors r+

**Pull request merged**
