### PR TITLE
Refactor break up procedure sql

### PR DESCRIPTION
**Pull request by ghost**
As discussed in #2051 splitting up the large procedures SQL file into smaller, more manageable files.

A good overview of the changes can be read in the comment here:
https://github.com/jambroo/bhima-2.X/blob/c294619a26082f78c14376791ee6e494ba79fec2/server/models/procedures.sql

### CODE REVIEW

**Comment by ghost** [comment]
Please bear with me I am just fixing this conflict..

**Comment by jniles** [comment]
No problem.  If you need any help, just chime in!  We merged about a months worth of a feature branch a few minutes ago, so I hope it isn't too big a merge...

**Review by jniles — APPROVED** [review]
Looks really good to me!  Using `source` was a great idea.

**Pull request merged**
