### PR TITLE
feat(lot origin): Remove lot registry feature

### LINKED ISSUE #1850: (refacor) ORIGINE DES LOTS
here are notices : 

1. this module seems like it can be removed without problem

2. seems like it does not show integrated lots

### LINKED ISSUE #2021: refactor(stock): update Stock Origins Registry to standards
References issue https://github.com/IMA-WorldHealth/bhima-2.X/issues/1737

The Stock Origins registry should be updated to meet the latest standards in order to reduce technical debt and give clients required features: 

- [ ] Use the latest `FilterService` in favour of the SearchFilterFormatService method
  - [ ] Update the StockService (maybe make a StockOriginService?) to use FilterService 
  - [ ] Update the search modal to use 'default' and 'custom' filters
- [ ] Integrate grid save state (https://github.com/IMA-WorldHealth/bhima-2.X/issues/1738)
  - [ ] Save configuration
  - [ ] Load default configuration
- [ ] "Menu" dropdown for core utilities
  * Column configuration
  * Download view as CSV
  * Download view as PDF 
- [ ] Use bhClear on search modal (https://github.com/IMA-WorldHealth/bhima-2.X/issues/1702)
- [ ] Ensure links to other registries work correctly

### PR DESCRIPTION
**Pull request by DedrickEnc**
This P.R request removes the feature lot registry as we can easily found the same information in others registries.

This PR closes #1850.  Closes https://github.com/IMA-WorldHealth/bhima-2.X/issues/2021.

### CODE REVIEW

**Comment by DedrickEnc** [comment]
@mbayopanda @jniles
Can you review this P.R ?

**Review by jniles — COMMENTED** [review]
Not much to review here. :+1:.

@mbayopanda, this one is for you to merge.  I'm not sure if this module is required or not, and you have more experience to know if one of the other registries can answer the same questions.  In my mind, fewer code is better!

**Comment by jniles** [comment]
Okay .. it has been a work week and @mbayopanda may be out of the action.  I'm merging this one and closing https://github.com/IMA-WorldHealth/bhima-2.X/pull/2053.  We can always reverse this decision later if we discover that we need it.

**Pull request merged**
