### PR TITLE
fix stock movement export to csv

### LINKED ISSUE #4329: Stock movements regsitry export to CSV links a broken PDF report.
The stock movements registry export to CSV tries to open a PDF report and it breaks.  Here is what that looks like:

4ndr3Z6Pjb

Note that this doesn't happen with the XLSX renderer.

### PR DESCRIPTION
**Pull request by mbayopanda**
This PR fix the issue #4329

Close #4329

### CODE REVIEW

**Comment by kwilu** [comment]
Hello @mbayopanda, it seems like you have referenced #4329 in your pull request description, but you have not referenced them in your commit message description(s). When you reference an issue in a commit message, it automatically closes the corresponding issue when the commit is merged.

Please run `git commit --amend` in your command line client to amend your commit message description with `Fixes #4329.`.

An example of a correctly-formatted commit:
```
commit fabd5e450374c8dde65ec35f02140383940fe146
Author: kwilu
Date:   Sat Mar 18 13:42:40 2017 -0700

    pull requests: Check PR commits reference when issue is referenced.

    Fixes #51.
```

Thank you for your contributions to BHIMA!

**Review by jniles — APPROVED** [review]
Great fix, thanks!

bors r+

**Comment by jniles** [comment]
Looks like a fluke.

bors r+

**Comment by jniles** [comment]
Hmmm... these stock movement tests are annoyingly flakey.  I wonder why.  Maybe it has to do with the ui-grid's grouping functionality?

Either way, going to try again.

Bors r+

**Pull request merged**
