### PR TITLE
chore: add installation tests to semaphore

### PR DESCRIPTION
**Pull request by jniles**
Adds installation tests to the semaphore testing regime. Removes them from Travis.

### CODE REVIEW

**Comment by jniles** [comment]
bors try

**Comment by jniles** [comment]
bors try

**Comment by jniles** [comment]
Excellent. This should reduce the test time.

Overall test time for the Semaphore CI run is 3:58. This is an increase of slightly less than 2 minutes.

This guts the installation tests run on Travis so that Travis can focus entirely on End to End tests.   This should speed up overall test runs.  Travis typically spends ~2-3 minutes building and running these tests.  Transferring them to Semaphore makes sense since they will not hog up precious resources over at Travis.

**Review by jmcameron — APPROVED** [review]
This looks okay to me.  But I'm not familiar with the semaphore or travis ci settings, so I cannot make an accurate judgement.  And it seems like the way to test this is with PRs.   So my suggestion is to go ahead with it and monitor it closely for a few days until it is clear that it working correctly.   (Trial by fire!)

**Comment by jniles** [comment]
Thanks @jmcameron.

As long as we trust the tests are doing the right thing, one way to verify that the runs are executing correctly is by doing "bors try".  What that does is merge master and the present branch, then run the tests and see if that returns a success code.

It would be good for us to walk through some of the testing infrastructure together at some point. I can see that being a real asset going forwards!

bors r+

**Comment by jniles** [comment]
Looks like https://github.com/IMA-WorldHealth/bhima/issues/4919 is hitting this.

bors r+

**Pull request merged**
