### PR TITLE
Feat: add search by inventory item to purchase registry

### LINKED ISSUE #4271: Add search by inventory item to purchase order registry
It would be nice to know which purchase orders have been made for a certain kind of product.  We should add a search field to the Purchase Order registry to filter purchase orders on an inventory item.  This would allow users to easily filter out what is on order without having to open up the purchase order to see.

### PR DESCRIPTION
**Pull request by jniles**
This PR adds the feature described in #4271.

The purchase registry can now be filtered on purchases that involve particular inventory items.  This should make it easier to track down where things came from.  Here is what it looks like in action:

1Msa87TeQS

Closes #4271.

### CODE REVIEW

**Comment by kwilu** [comment]
Hello @jniles, it seems like you have referenced #4271 in your pull request description, but you have not referenced them in your commit message description(s). When you reference an issue in a commit message, it automatically closes the corresponding issue when the commit is merged.

Please run `git commit --amend` in your command line client to amend your commit message description with `Fixes #4271.`.

An example of a correctly-formatted commit:
```
commit fabd5e450374c8dde65ec35f02140383940fe146
Author: kwilu
Date:   Sat Mar 18 13:42:40 2017 -0700

    pull requests: Check PR commits reference when issue is referenced.

    Fixes #51.
```

Thank you for your contributions to BHIMA!

**Review by lomamech — COMMENTED** [review]
Very Good 
No comment 
image

**Comment by kwilu** [comment]
Heads up @jniles, we just merged some commits that conflict with the changes your made in this pull request! You can review this repository's [recent commits](https://github.com/IMA-WorldHealth/bhima/commits/master) to see where the conflicts occur. Please rebase your feature branch against the `upstream/master` branch and [resolve](https://zulip.readthedocs.io/en/latest/git/troubleshooting.html#recover-from-a-git-rebase-failure) your pull request's merge conflicts accordingly.

**Comment by lomamech** [comment]
@jniles This branch is in conflict with the master branch, fix it and i will merged

**Comment by lomamech** [comment]
@jniles the Travis CI - Pull Request failing
image

**Comment by jniles** [comment]
@lomamech, yeah, I'll have to update it.  I'll ping you in a bit when it works.

**Comment by jniles** [comment]
@lomamech I'm pretty sure this is going to pass now.

**Pull request merged**
