### PR TITLE
Feat: add link to account statement report

### LINKED ISSUE #4483: Add link to account statement on account dropdown in Account Management
I was curious if some blocked accounts had remaining balances.  I'm lazy and don't want to look them up in the Simple Account statement report.  Let's put a link in the Account Management dropdown that takes me to the Simple Account Statement report and populates it with the account number selected.

image

### PR DESCRIPTION
**Pull request by jniles**
~~Adds links to the non-title accounts to view the account statement report.~~

Adds links to the non-title accounts to view the **simple account PDF report**.

Close #4483.

Here is what it looks like in action.
Z5E1FT8rej

### CODE REVIEW

**Review by mbayopanda — COMMENTED** [review]
The link works perfectly with the account statement registry, i am wondering just how to be sure about values in the account statement registry since we limit the result to just 1000 records.

A link to the report `Rapport de compte simple` will be nice

**Comment by jniles** [comment]
@mbayopanda thanks for the review.

Do you want it to link directly to the PDF report or to the module?  Currently, we don't have any way (to my knowledge) of setting the report parameters through `$stateParams` for any report, but I could link the PDF directly.

**Comment by mbayopanda** [comment]
@jniles the what about the link to a PDF, is it possible to do that currently ?

**Comment by jniles** [comment]
Changes landed!

**Review by mbayopanda — APPROVED** [review]
LGTM 👍 

bors r+

**Pull request merged**
