### PR TITLE
chore(i18n): refactor en.json key

### PR DESCRIPTION
**Pull request by AdamWatts**
For issue 

Closes https://github.com/IMA-WorldHealth/bhima-2.X/issues/3100

### CODE REVIEW

**Comment by jniles** [comment]
Nice @AdamWatts!  Looks like the tests pass muster online.  We'll post a suitable translation and then get this merged 👍

**Comment by AdamWatts** [comment]
@jniles Nice, Thank you :)

**Comment by jniles** [comment]
@mbayopanda, can you provide a French translation for this change?

**Comment by jniles** [comment]
Beautiful.  Thanks to both of you! 

bors r+

**Comment by AdamWatts** [comment]
Delete the branch?

**Comment by jniles** [comment]
Sure!  It won't harm anything.

**Comment by sfount** [comment]
@AdamWatts Congrats on closing your first issue! :tada:

**Comment by AdamWatts** [comment]
@sfount Thanks for the help!

**Pull request merged**
