### PR TITLE
Using debtor

### PR DESCRIPTION
**Pull request by lomamech**
Using debtor instead of debitor

@sfount

### CODE REVIEW

**Comment by sfount** [comment]
@jniles this re-factor was originally proposed by you.

**Comment by jniles** [comment]
@lomamech, I have three failing end to end tests in the patient registration module:

``` sh
  1) patient registration successfully registers a valid patient:
     NoSuchElementError: No element found using locator: by.model("PatientRegCtrl.finance.debitor_group_uuid")

  2) patient registration form validation correctly blocks invalid form submission with relevent error classes:
     NoSuchElementError: No element found using locator: by.model("PatientRegCtrl.finance.debitor_group_uuid")

  3) patient registration form validation correctly identifies duplicate hospital numbers (async):

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true
```

This is a really good refactor.  It looks like there are a few tests to update, and then I'll merge it.

**Comment by lomamech** [comment]
Fix error arround PatientRegCtrl.finance.debitor_group_uuid in test E2E for patient registration 

@sfount   @jniles

**Comment by jniles** [comment]
@lomamech, thanks.  ~~Running the test again.~~ **Tests pass!**

**Comment by jniles** [comment]
LGTM.  Thanks for this hard work!

**Pull request merged**
