### PR TITLE
chore(stock): combine credit lines in stock exit movement

### LINKED ISSUE #3962: Distibution to Patient's voucher writes a lot of lines to credit stock account
I'm poking through some of the live data and it looks like we are writing two lines line of stock distributed.  It would be useful to only have a single line leaving the depot (if possible).

This is what it looks like below:
image

Can we do better?

### PR DESCRIPTION
**Pull request by jniles**
This commit combines the credit lines in the voucher of the stock movement to ensure that we aren't recording many more lines in the posting journal than we need to.  You can see the difference below - instead of three lines for stock distribution crediting the stock account, we have a single line.

**Before**
image

**After**
image

Closes #3962.

### CODE REVIEW

**Comment by jniles** [comment]
@lomamech can I get a review?

**Comment by jniles** [comment]
@mbayopanda, since @lomamech isn't feeling well, could you take a look that this PR?

**Review by mbayopanda — APPROVED** [review]
It works as expected.

LGTM 👍 

bors r+

**Comment by mbayopanda** [comment]
bors try

**Pull request merged**
