### PR TITLE
refractor(stock inventory) ajust modal-body padding

### LINKED ISSUE #3243: Stock lots search panel has too much padding
There is a bit too much padding on the stock lots search panel.   See below:
stock - search has too much padding
_Fig 1: Stock Lots Search_

### PR DESCRIPTION
**Pull request by jeremielodi**
closes #3243

### CODE REVIEW

**Comment by jniles** [comment]
Can you put a screenshot?

**Comment by jeremielodi** [comment]
lotsearch

**Comment by jniles** [comment]
LGTM.

bors r+

**Comment by jniles** [comment]
bors try

**Comment by jniles** [comment]
@jeremielodi, can you try and track down these failures?  They seem tied to most other PRs.

**Pull request merged**
