### PR TITLE
refactor(stock): remove stock entry search range in search modal

### LINKED ISSUE #5186: "Entry date" and "Period" (in filters by default) do the same thing in Stock Lots Search Modal
We have multiple options for searching for dates in the Lots Search modal.  Not all of them make sense.  It appears that the "Period" is the same thing as the "Entry Date".  I propose we change the text on the "Period" to be "Entry Period" or "Entry Date", default that to "allTime" and remove the "Entry Date" search.

image

image

### PR DESCRIPTION
**Pull request by jniles**
Removes the stock entry filter for the period filter instead.

Closes #5186.

### CODE REVIEW

**Review by jmcameron — CHANGES_REQUESTED** [review]
Code looks good.

I tested this and I think it makes sense and simplifies things.

However, I was confused when I first looked at the search form because there are just two empty date boxes below "Date d'expiration".   If you think about it or cnce you try some of the given time ranges, it makes sense.  However, I wonder if the boxes could initially display greyed-out 'Start date' and 'End date', respectively.   That would make it really clear.

One problem I encountered:  When I clicked on "This week", I got the little orange indicator "This Week" by Expiration Date.  Nice.  However, when I clear it (link right end above 'end date' field) the indicator was not erased.   Same for "Today", etc.

**Comment by jniles** [comment]
@jmcameron you are right.  This is an issue with the date range more generally.  Would you like me to address it in the PR or a different one?

**Comment by jmcameron** [comment]
Let's make it a separate Issue since it will affect multiple pages.

-Jonathan

**Review by jmcameron — APPROVED** [review]
Looks good.  I'll add in issue about the "Start date" "end date" placeholders in the bhDateInterval component.

**Comment by jniles** [comment]
Based on @jmcameron's approval, I am merging this.

bors r+

**Pull request merged**
