### PR TITLE
Sorting inventory by quantity to command

### LINKED ISSUE #4629: Allow sorting by "commandes" in the Articles in Stock registry
It would be useful to sort by the "commandes" column in the articles in stock registry.  This column contains the number of items to reorder to get to the maximum stock level.  Sorting it would let users identify which stock items are lacking most.  

image

### PR DESCRIPTION
**Pull request by mbayopanda**
image

Close #4629

### CODE REVIEW

**Comment by kwilu** [comment]
Hello @mbayopanda, it seems like you have referenced #4629 in your pull request description, but you have not referenced them in your commit message description(s). When you reference an issue in a commit message, it automatically closes the corresponding issue when the commit is merged.

Please run `git commit --amend` in your command line client to amend your commit message description with `Fixes #4629.`.

An example of a correctly-formatted commit:
```
commit fabd5e450374c8dde65ec35f02140383940fe146
Author: kwilu
Date:   Sat Mar 18 13:42:40 2017 -0700

    pull requests: Check PR commits reference when issue is referenced.

    Fixes #51.
```

Thank you for your contributions to BHIMA!

**Comment by jmcameron** [comment]
Should some of the other columns support sorting too?

**Review by jniles — APPROVED** [review]
Satisfies the issue and looks good to me.

bors r+

**Comment by jniles** [comment]
@jmcameron potentially.  I can't think of a use case where I would want to sort the other non-sortable columns, but it is easy to do if our users need/want it (as demonstrated in this PR).

The main reason for sorting this one is to figure out what is the most stock I'll need to reorder.  All the other columns are based off the CMM, so as long as we can sort the CMM, it should actually sort the rest of the columns as well.

**Comment by jniles** [comment]
Bors r+

**Pull request merged**
