### PR TITLE
Add database port in the database build script

### PR DESCRIPTION
**Pull request by mbayopanda**
This PR adds the database port in the database build script which will help to switch easily to a different version of MySQL by its running port

### CODE REVIEW

**Comment by jniles** [comment]
Not a bad idea.  Can you add this to the `.env.sample`?  And change the `build-init-database.sh` script?

It might also be useful to have a straightforward default value.  You can do this in bash by putting:
```sh
DB_PORT=${DB_PORT:-3306}
```
at the top of the `.sh` scripts.

**Comment by jniles** [comment]
Looks like it is just `.env.sample` that needs to be updated, then we can merge this.

**Comment by mbayopanda** [comment]
Here is .env.sample : 
image

We already have: `DB_PORT` defined

**Comment by jniles** [comment]
Oh!  Didn't realize it was already there.  My apologies.

bors r+

**Pull request merged**
