### PR TITLE
Test(Component Date Editor)

### LINKED ISSUE #4889: Problematic for the E2E test of the bh-date-editor component
There is a problem for when we try to write the E2E test using the bh-date-editor component, indeed if we analyze the code that allows testing on the component, we realize that 'there is a click on the **.header-image** element, while this element is not visible when using the component in a modal window

### PR DESCRIPTION
**Pull request by lomamech**
- Addition of a new parameter to solve the problem of the date editor
component for forms whose .header-image is not visible by adding a new
component
- Use bhDateEdit in Off Days E2E test

closes #4889

### CODE REVIEW

**Review by jeremielodi — APPROVED** [review]
Good job @lomamech, thanks

**Comment by jeremielodi** [comment]
bors try

**Comment by jniles** [comment]
bors try

**Comment by jeremielodi** [comment]
@jniles I solved this problem(bhDateEditor bug) in #4837
Don't worry if this fails

**Comment by jniles** [comment]
Oh!  Can this PR be closed then?

**Comment by jeremielodi** [comment]
Not yet, I just arranged the dateEditor ent-to-end test bug

**Comment by jeremielodi** [comment]
@jniles you can merge if the bors passes successfully

**Pull request merged**
