### PR TITLE
bug(Recalculate Monthly Average Consumption)

### LINKED ISSUE #4188: Recalculation of average consumption Monthly
This Issue proposes to recalculate monthly consumption by six months past consumption

### PR DESCRIPTION
**Pull request by lomamech**
- Improvement of how the average monthly consumption for the last six
  months is calculated

closes #4188

### CODE REVIEW

**Comment by lomamech** [comment]
@jeremielodi can you review

**Comment by lomamech** [comment]
@mbayopanda It is likely that @jeremielodi  is taken in the work of the iHRIS project, if possible think of the review as well as the update of the version of Bhima in Tshikaji but also in Vanga since we are in a new fiscal year

**Comment by mbayopanda** [comment]
@lomamech yes i'll do... he's working on that

**Comment by mbayopanda** [comment]
@lomamech c'est quoi ce fichier ? server/controllers/inventory/controllers - Raccourci.lnk ??

**Comment by jeremielodi** [comment]
@lomamech in what BHIMA module are you analysing the result for this PR.
The only place I see we use avg_consumption(CMM) is at stok lots (lots en stock) and I notice that the value is not calculate manually in nodejs but it comes from sql
```sql
    SELECT BUID(l.uuid) AS uuid, l.label, l.initial_quantity,
      SUM(m.quantity * IF(m.is_exit = 1, -1, 1)) AS quantity,
      d.text AS depot_text, l.unit_cost, l.expiration_date,
      ROUND(DATEDIFF(l.expiration_date, CURRENT_DATE()) / 30.5) AS lifetime,
      BUID(l.inventory_uuid) AS inventory_uuid, BUID(l.origin_uuid) AS origin_uuid,
      i.code, i.text, BUID(m.depot_uuid) AS depot_uuid,
      m.date AS entry_date,
      i.avg_consumption, i.purchase_interval, i.delay,
      iu.text AS unit_type,
      ig.name AS group_name, ig.expires,
      dm.text AS documentReference
    FROM stock_movement m
    JOIN lot l ON l.uuid = m.lot_uuid
    JOIN inventory i ON i.uuid = l.inventory_uuid
    JOIN inventory_unit iu ON iu.id = i.unit_id
    JOIN inventory_group ig ON ig.uuid = i.group_uuid
    JOIN depot d ON d.uuid = m.depot_uuid
    LEFT JOIN document_map dm ON dm.uuid = m.document_uuid
```
AND in the grid I have <b>1</b> every where
lots

I don't see also where this API <b>/stock/consumptions/average/:periodId</b> is called in the client side

**Comment by mbayopanda** [comment]
@jeremielodi `server/controllers/stock/core.js` in the `getStockConsumption()` function

**Review by jeremielodi — APPROVED** [review]
LGTM good work

**Comment by mbayopanda** [comment]
Already done

**Pull request closed without merging**
