### PR TITLE
fix(reports): aged debtor totals

### LINKED ISSUE #3209: Aged Debtors Report has nonsense totals when grouped by months
The Aged Debtors Report is supposed to give a client's balanced, grouped by months or periods.  When grouped by months, however, the report produces very strange values.  Here is the result:

**Grouped By Months**
incorrectageddebtorsreport

**Grouped by Period**
correctageddebtorsreport

### PR DESCRIPTION
**Pull request by jniles**
This commit fixes the Aged Debtors report totals so that they respect the fiscal year range.

Closes #3209 

fixedageddebtors

### CODE REVIEW

**Comment by jniles** [comment]
Looks like this also affects Aged Creditors as well.   I'll include a fix.

**Comment by jniles** [comment]
Okay, fixed a few bugs on the Aged Creditors report, including this one.  

**Aged Creditors Before**
agedcreditorsbefore

**Aged Creditors After**
agedcreditorsafter

**Comment by jniles** [comment]
@mbayopanda, can I get a review?

**Review by mbayopanda — COMMENTED** [review]
What do you think of having for monthly group columns ordered like : 

| Nom | Numero de compte | Autres mois | mois N-2 | mois N-1 | mois N | Total |
| ---     | ---                            | ---                | ---           | ---           | ---         | ---    |

For example if the selected period is September : 

| Nom | Numero de compte | Autres mois | Juillet | Aout | Septembre | Total |
| --- | --- | --- | --- | --- | --- | --- |
| CENTRE HOSPITALIER JUKAYI | 40111010 | $1000.00 | $10.00 | $10.00 | $219.54 | $1239.54 |

Because i think this presentation is naturally readable instead of figuring out how to read the table

**Comment by jniles** [comment]
Alright, will make the updates and report back.  Thanks for the review!  :+1:

**Review by mbayopanda — APPROVED** [review]
The code looks good and also totals are corrects.

LGTM 👍

**Comment by jniles** [comment]
New Format:

newageddebtorreport

**Comment by jniles** [comment]
@mbayopanda changes landed!

**Pull request merged**
