### PR TITLE
Design the patient Card for the patient Record

### LINKED ISSUE #633: (design) Patient Card
The current patient card in 2.x is simply a prototype.  The design below shows a better version of the patient card to be implemented before rollout.

patient card
_Fig 1: Patient Card_

The barcode is purely optional.  If we ever do implement barcodes, we should be able to match it to the binary patient UUID.

The patient card should be printed out on A5 paper.

Note: The bottom left hand corner is the astrological gender symbol and the date of birth.  It might make better sense to either substitute these for the hospital number or add the hospital number as well.

### PR DESCRIPTION
**Pull request by lomamech**
Design the patient Card for the patient Record

Nota: no way to use glyphicon-icon-male or glyphicon-icon-female

Closes #633.

@jniles

### CODE REVIEW

**Comment by jniles** [comment]
@lomamech, could you include a screenshot?

**Comment by lomamech** [comment]
screnshoot

**Comment by lomamech** [comment]
The screenshot
@jniles

**Comment by jniles** [comment]
@lomamech, thanks.

The ID TPATPA3 is not correct.  Please show the patient's correct ID `TPA3`.  Could you also use `text-right` to make the ID text align to the right of the card?

Could you try to fit the patient's name all on one line?  It would look much better.

Seeing this card, I think a more appropriate size for the paper is A6 (the original size before the suggested change in #633).  How does it look on an A6 page?

**Comment by lomamech** [comment]
Improve patient card, using div instead table And changing page size A6 instead A5

@jniles

**Comment by jniles** [comment]
LGTM!

**Comment by jniles** [comment]
Hmm...  the patient card doesn't work on my machine.  @lomamech, does it work for you on master?

**Pull request merged**
