### PR TITLE
Remove service.id and replace it with service.uuid

### LINKED ISSUE #4104: Do we need service.uuid and service.id?
We have both a service uuid and a service ID column.  It isn't clear why this is the case.  Do we really need both columns?  Can we remove one and use the other instead?

### PR DESCRIPTION
**Pull request by jniles**
This PR implements the changes requested in #4104.  It removes the service.id column and replaces its use with the service.uuid column.

This PR is still a work in progress.  In particular, it should not be merged until there is a migration script that works for different institutions.

Closes #4104.

### CODE REVIEW

**Comment by kwilu** [comment]
Hello @jniles, it seems like you have referenced #4104 in your pull request description, but you have not referenced them in your commit message description(s). When you reference an issue in a commit message, it automatically closes the corresponding issue when the commit is merged.

Please run `git commit --amend` in your command line client to amend your commit message description with `Fixes #4104.`.

An example of a correctly-formatted commit:
```
commit fabd5e450374c8dde65ec35f02140383940fe146
Author: kwilu
Date:   Sat Mar 18 13:42:40 2017 -0700

    pull requests: Check PR commits reference when issue is referenced.

    Fixes #51.
```

Thank you for your contributions to BHIMA!

**Comment by jniles** [comment]
@mbayopanda can I get a review?

I've tested migrating both the vanga and the IMCK database with this.  It seems to work as far as I can tell.  Let me know if you find any issues.

**Review by mbayopanda — COMMENTED** [review]
Here are some errors that I got : 

image
In : http://localhost:8080/#!/reports/realizedProfit 

image
In : http://localhost:8080/#!/reports/visit_report

image
In : http://localhost:8080/#!/reports/employeeStanding

image
In : http://localhost:8080/#!/reports/breakEvenFeeCenter

image
In : http://localhost:8080/#!/reports/indicatorsReport

**Comment by jniles** [comment]
@mbayopanda thanks for the review!  This is very thorough.  Let me get on fixing these and I'll ping you back.

**Comment by jniles** [comment]
I can't reproduce any of these.  Did you run the migration script on your database?

**Review by mbayopanda — APPROVED** [review]
The migration file is working so well 👍 

bors r+

**Pull request merged**
