### PR TITLE
chore(schema): drop odk_app_user

### PR DESCRIPTION
**Pull request by jniles**
This commit removes the odk_app_user table.  I am pretty sure it is no longer being used, as I could not find any code that referenced it.

### CODE REVIEW

**Review by jmcameron — APPROVED** [review]
The code changes are clear and do not appear to affect anything else.

All tests pass.

But I would like @mbayopanda to let us know if this table is used by anyone before merging.

**Review by mbayopanda — APPROVED** [review]
👍🏽 LGTM

**Comment by mbayopanda** [comment]
@jniles Could you update the branch with the base branch please

**Comment by jniles** [comment]
Rebased and ready for merge.

**Pull request merged**
