### PR TITLE
refractor(session service) using $state instead of $location

### LINKED ISSUE #3030: Update SessionService to use $state instead of $location
The `SessionService` manages the user's session on the client.  When the session is logged out, the service redirects the user to the `/login` URL using $location.  Since we've mostly lifted navigation from angular's `$location` service to use ui-router's `$state` service, it would make sense that we also switch these calls to using `$state` for uniformity.

### PR DESCRIPTION
**Pull request by jeremielodi**
closes #3030

### CODE REVIEW

**Comment by jniles** [comment]
Looks like the SessionService tests need to be updated before this will pass.  Could you take look at them?

**Review by jniles — APPROVED** [review]
Looks good to me!

bors r+

**Comment by jniles** [comment]
@jeremielodi, looks like the most recent changes to the master branch have broken these tests.  Can you try to resolve these?

**Comment by jeremielodi** [comment]
ok, let me give it a try

**Pull request merged**
