### PR TITLE
Remove unused property description for transanction_type

### LINKED ISSUE #1582: (refactor) Remove Transaction Type descriptions
It doesn't seem to me that there is any use in the Transaction Type description .. if anything they make things more confusing.  I propose that we remove them from the database and make transaction types simply a label ... most of the time the label is descriptive enough.  If a client ever asks for the description, we can add it in later.

### PR DESCRIPTION
**Pull request by lomamech**
Remove unused property description for transanction_type

closes #1582

### CODE REVIEW

**Comment by jniles** [comment]
Tagging @mbayopanda because he worked on these files.

@mbayopanda, do you think this proposal is a good idea, or do you see a use for the description field?

**Review by mbayopanda — APPROVED** [review]
The description of transaction type is nicely removed.

LGTM

**Comment by jniles** [comment]
Code LGTM :+1:

**Review by jniles — APPROVED** [review]

**Comment by jniles** [comment]
Code LGTM :+1:

**Pull request merged**
