### PR TITLE
Fee center schema and API

### PR DESCRIPTION
**Pull request by DedrickEnc**
This PR adds an initial schema and API to continue the feature developing
Here are things to notice in this PR : 

- The table ```cost_center``` and ```profit_center``` are deleted
-  A new table ```fee_center``` is created```
- The modules cost center and profit center are deleted
- The service module is updated to fit with the  changes
- The delete functionality is not yet implemented and the integration  test for this functionality is ignored, because we did not talk about that during the design. 
Thank you for contributing!

Before submitting this pull request, please verify that you have:
 - [x] Run your code through JSHint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
 - [x] Run integration tests.
 - [x] Run end-to-end tests.
 - [x] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

### CODE REVIEW

**Comment by DedrickEnc** [comment]
@sfount

**Comment by sfount** [comment]
Why does this pull request include 9 commits from other developers?

It is not clear what code should be reviewed when there are 53 files changed.

**Comment by jniles** [comment]
@dedrickenc, this is a very easy mistake to make and  problem to solve.  I just did it on a separate branch (see [this PR](https://github.com/Vanga-Hospital/bhima-2.X/pull/130) for the mistake and [this PR](https://github.com/Vanga-Hospital/bhima-2.X/pull/132) for the correction).

You want to use [git cherry-pick](https://git-scm.com/docs/git-cherry-pick).  It should look something like this:
```sh
# make sure you branch from master when creating your new branch.
git checkout -b fee-center-api master

# this is the id of your first commit that you made.
git cherry-pick 0fbcdcd61060006b46f9f4d823a566b3c5dbff28

# ... do the same thing for the rest, cherry-picking each commit one at a time.

# push back up and open a new pull request
git push origin fee-center-api
```

**Comment by DedrickEnc** [comment]
Sorry for the mistake, I think it is just a problem of rebasing, I Will correct it!Envoyé depuis mon mobile Huawei-------- Message original --------Objet : Re: [IMA-WorldHealth/bhima-2.X] Fee center schema and API (#1100)De : Jonathan Niles À : "IMA-WorldHealth/bhima-2.X" Cc : Dedrick Kitamuka ,Mention @dedrickenc, this is a very easy mistake to make and  problem to solve.  I just did it on a separate branch (see this PR for the mistake and this PR for the correction).
You want to use git cherry-pick.  It should look something like this:
# make sure you branch from master when creating your new branch.
git checkout -b fee-center-api master

# this is the id of your first commit that you made.
git cherry-pick 0fbcdcd61060006b46f9f4d823a566b3c5dbff28

# ... do the same thing for the rest, cherry-picking each commit one at a time.

# push back up and open a new pull request
git push origin fee-center-api

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/IMA-WorldHealth/bhima-2.X","title":"IMA-WorldHealth/bhima-2.X","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/IMA-WorldHealth/bhima-2.X"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jniles in #1100: @dedrickenc, this is a very easy mistake to make and  problem to solve.  I just did it on a separate branch (see [this PR](https://github.com/Vanga-Hospital/bhima-2.X/pull/130) for the mistake and [this PR](https://github.com/Vanga-Hospital/bhima-2.X/pull/132) for the correction).\r\n\r\nYou want to use [git cherry-pick](https://git-scm.com/docs/git-cherry-pick).  It should look something like this:\r\n```sh\r\n# make sure you branch from master when creating your new branch.\r\ngit checkout -b fee-center-api master\r\n\r\n# this is the id of your first commit that you made.\r\ngit cherry-pick 0fbcdcd61060006b46f9f4d823a566b3c5dbff28\r\n\r\n# ... do the same thing for the rest, cherry-picking each commit one at a time.\r\n\r\n# push back up and open a new pull request\r\ngit push origin fee-center-api\r\n```"}],"action":{"name":"View Pull Request","url":"https://github.com/IMA-WorldHealth/bhima-2.X/pull/1100#issuecomment-272422130"}}}

**Pull request closed without merging**
