### PR TITLE
chore(deps): remove puppeteer in favor of coral

### PR DESCRIPTION
**Pull request by jniles**
Migrates to using `@ima-worldhealth/coral` as a PDF renderer.  Now we share the same PDF renderer across multiple projects (sunfish, ima-data, bhima) and can test and do upgrades in a unified fashion.

### CODE REVIEW

**Comment by jniles** [comment]
@lomamech can I get a review?

**Review by lomamech — COMMENTED** [review]
The changes are simple, it's just a question of solving the conflict with branch Master

**Comment by jniles** [comment]
Thanks @lomamech, I'll do a rebase and come back to you.

**Comment by jniles** [comment]
@lomamech, I've rebased after our most recent merges.  It should be ready  to go.

**Pull request merged**
