### PR TITLE
refactor(journal): Better transaction editing i18n text

### PR DESCRIPTION
**Pull request by jniles**
Some feedback remarked that the button texts were not very clear.  The translations have been
updated, as well as using the translate directive for performance reasons.  The following has
changed:
 1. Write "Save" on the save transaction button.
 2. "Refresh the filter" is now "Remove the filters"

Partially addresses commentary in #1499.

---
Thank you for contributing!

Before submitting this pull request, please verify that you have:
 - [x] Run your code through ESLint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
 - [x] Run integration tests.
 - [x] Run end-to-end tests.
 - [x] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

### CODE REVIEW

**Comment by jniles** [comment]
@kwilu r+

**Comment by ghost** [comment]
:pushpin: Commit 3a6f633 has been approved by `jniles`

**Comment by ghost** [comment]
:hourglass: Testing commit 3a6f6339f2bdd6ef6bf49e3f912f8792311f8163 with merge 82d209a0d5e46b0a39abaebc562e03a27e7551cd...

**Comment by ghost** [comment]
:hourglass: Testing commit 3a6f6339f2bdd6ef6bf49e3f912f8792311f8163 with merge 967f85452891c3b36c86b4d6d6121ebf628dec49...

**Comment by ghost** [comment]
:hourglass: Testing commit 3a6f6339f2bdd6ef6bf49e3f912f8792311f8163 with merge f4d860f9fe790fd642391ac284358d18cd584a56...

**Comment by jniles** [comment]
@kwilu, I don't think you will ever stop..

**Pull request merged**
