### PR TITLE
fix(inventory): reverse COGS & asset accounts

### LINKED ISSUE #4798: Test database stock/expense accounts are backwards.
In our test database, we have our stock and expense accounts backwards.  See below:
image

The stock asset account is the 3* accounts and the stock expense accounts should be the 6* accounts.

### PR DESCRIPTION
**Pull request by jniles**
Fixes the test database by reversing the cost-of-goods-sold (COGS) expense accounts and the asset accounts.  Here is the fixed version:

image

Closes #4798.

### CODE REVIEW

**Review by mbayopanda — APPROVED** [review]
LGTM 👍

**Comment by jniles** [comment]
@mbayopanda I need to update the test cases before this passes :)

**Pull request merged**
