### PR TITLE
fix docs, currently only MySQL 5.7 is supported

### LINKED ISSUE #4457: MySQL 5.6 not supported
noticed when working on #2090:
the version 5.6 of MySQL is not supported because the `JSON` type was only introduced in 5.7 https://dev.mysql.com/doc/refman/5.7/en/json.html

What to do? Trying to be downward compatible or delete 5.6 out of the documentation?

### PR DESCRIPTION
**Pull request by individual-it**
fixes #4457  

-----
[View rendered docs/en/for-developers/installing-bhima.md](https://github.com/individual-it/bhima/blob/fixDocsMySQLVersion/docs/en/for-developers/installing-bhima.md)
[View rendered docs/fr/for-developers/installing-bhima.md](https://github.com/individual-it/bhima/blob/fixDocsMySQLVersion/docs/fr/for-developers/installing-bhima.md)

### CODE REVIEW

**Comment by kwilu** [comment]
Hello @individual-it, it seems like you have referenced #4457 in your pull request description, but you have not referenced them in your commit message description(s). When you reference an issue in a commit message, it automatically closes the corresponding issue when the commit is merged.

Please run `git commit --amend` in your command line client to amend your commit message description with `Fixes #4457.`.

An example of a correctly-formatted commit:
```
commit fabd5e450374c8dde65ec35f02140383940fe146
Author: kwilu
Date:   Sat Mar 18 13:42:40 2017 -0700

    pull requests: Check PR commits reference when issue is referenced.

    Fixes #51.
```

Thank you for your contributions to BHIMA!

**Comment by individual-it** [comment]
@kwilu done

**Review by jniles — APPROVED** [review]
Much better.  :+1:

**Pull request merged**
