### PR TITLE
Stock inventory feature

### PR DESCRIPTION
**Pull request by mbayopanda**
This PR add a new way of performing stock inventory : 
- By removing all previous stock of a the selected depot
- By adding new stock as the real stock

### CODE REVIEW

**Comment by jniles** [comment]
@mbayopanda I took a look at this, and I don't think this the functionality Vanga wanted.  This is my fault - I didn't specify the issue #4076 well.

They are used to having a giant registry like the stock lots module that shows every lot in the depot.  It would look something like this:
Stock Inventory Adjustment

I've updated the issue to show this.

The idea is that it should look like the inventory fiche they use to calculate stock on the shelf.  No need for a date or even a description.  We can generate both of those automatically.

**Comment by mbayopanda** [comment]
@jniles what if there are lots in the real depot and not in bhima ? How to add them during the inventory adjustment ?

**Comment by jniles** [comment]
@mbayopanda, I would say we ignore that case for the moment.  We will still have the other adjustment module for a time.

**Comment by kwilu** [comment]
Heads up @mbayopanda, we just merged some commits that conflict with the changes your made in this pull request! You can review this repository's [recent commits](https://github.com/IMA-WorldHealth/bhima/commits/master) to see where the conflicts occur. Please rebase your feature branch against the `upstream/master` branch and [resolve](https://zulip.readthedocs.io/en/latest/git/troubleshooting.html#recover-from-a-git-rebase-failure) your pull request's merge conflicts accordingly.

**Comment by mbayopanda** [comment]
There is new one #4369 which is a refactoring

**Pull request closed without merging**
