### PR TITLE
feat(migration) add posted column in invoice and cash tables

### PR DESCRIPTION
**Pull request by jeremielodi**
posted column had to be added in invoice and cash tables

### CODE REVIEW

**Comment by kwilu** [comment]
Heads up @jeremielodi, we just merged some commits that conflict with the changes your made in this pull request! You can review this repository's [recent commits](https://github.com/IMA-WorldHealth/bhima/commits/master) to see where the conflicts occur. Please rebase your feature branch against the `upstream/master` branch and [resolve](https://zulip.readthedocs.io/en/latest/git/troubleshooting.html#recover-from-a-git-rebase-failure) your pull request's merge conflicts accordingly.

**Comment by jniles** [comment]
@jeremielodi, can you fix the conflicts in this PR?

**Comment by kwilu** [comment]
Heads up @jeremielodi, we just merged some commits that conflict with the changes your made in this pull request! You can review this repository's [recent commits](https://github.com/IMA-WorldHealth/bhima/commits/master) to see where the conflicts occur. Please rebase your feature branch against the `upstream/master` branch and [resolve](https://zulip.readthedocs.io/en/latest/git/troubleshooting.html#recover-from-a-git-rebase-failure) your pull request's merge conflicts accordingly.

**Comment by jniles** [comment]
~~@jeremielodi, does this need to be updated before the IMCK upgrade?~~

Looks like it is required from my tests.  I'll go ahead and fix this up.

**Pull request merged**
