### PR TITLE
refactor(bhFindPatient): make bhFindPatient inline

### LINKED ISSUE #274: Improve bhFindPatient
This issues tracks further refinements to the `bhFindPatient` component.  Any further suggestions should be made in the comments and will be added to the following checklist.
- [ ] Break the `bhFindPatient` component into two components and templates (inline and default) that use the same controller.  We have not used the default "panel" form yet (although we likely will), so it would be easier to maintain if we split these up.
- [ ] The `typeahead` should display a loading indicator in the template body if the typeahead is loading data for a better UX.
- [x] The "Patient Not Found" text (Find By Name) should be `text-danger` and floated to the left.
- [x] The "Patient Not Found" text (Find By ID) should be `text-danger`.  The refresh button should share the same `border-color: #a94442` as the rest of the input.  See below:
  
  **Current Behavior**
  findpatientdefaultbehavior
  **Proposed Behavior**
  findpatientproposedbehavior

### PR DESCRIPTION
**Pull request by jniles**
This commit removes the option to switch between inline and panel versions of the bhFindPatient component as the panel version has not been used to date.  It also refactors both the documentation and the code to ensure that the component is up to date with the latest standards.

**Important Changes**
1. `$ctrl.reload()` is now called `$ctrl.reset()`.  It was always called `reset()` from the external API's perspective, I've changed all internal references to `reset()`.
2. Form validation now colors the `control-label`.
3. No more `type="inline"` or `type="panel"`.  This option has been removed, and the component is always `inline`.

Closes #274.

---

Thank you for contributing!

Before submitting this pull request, please verify that you have:
- [x] Run your code through JSHint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
- [x] Run integration tests.
- [x] Run end-to-end tests.
- [x] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

### CODE REVIEW

**Comment by sfount** [comment]
@jniles This re-factor LGTM!

Your pull request is set up to close https://github.com/IMA-WorldHealth/bhima-2.X/issues/274 however there is a comment in that thread mentioning this component being covered by karma tests. 

Either you can add unit tests covering this component in this pull request or remove the 'closes' line and this will be merged with the unit tests added in the future. This is completely up to you! Which would work best for now?

**Comment by jniles** [comment]
@sfount, thanks for pointing that out.  I'll write some unit tests to address #274 , and update this PR.  I'll let you know when I need another review.

**Comment by jniles** [comment]
@sfount, I've added controller tests.  They are in `bhFindPatient/controller.spec.js`.  I've added the basic structure of DOM tests (to handle `ng-click`s, `ng-change`s, and `ng-keypress` events) to the `bhFindPatient/dom.spec.js` file, but they are skipped, as Karma is not registered all clicks for some reason.  Once I track down that bug, I'll fix it.  But for now, these tests should be enough to close #274.

**Comment by jniles** [comment]
@sfount, can I get a review?

**Comment by sfount** [comment]
@jniles unit tests look good to me, this can close #274. Great re-factor.

**Comment by jniles** [comment]
@sfount, rebased.

**Pull request merged**
