### PR TITLE
feat(patients): group changes on financial status

### LINKED ISSUE #5487: Display changes in debtor group on the Patient Financial Activity
We should show when a patient changes debtor group in-line on the Patient Financial Activity report.

There was a particularly hairy analysis that I needed to perform for our partners in Vanga because of patients that had been invoiced in multiple debtor groups.  This was not at all evident from their financial activity history and it _looked_ like they had done all their transactions correctly in the debtor group's account.

Let's work around this by making it very obvious when the patient changes a debtor group by dedicating an entire `<tr>` to the fact that the debtor changed groups within that time.  It should be something like `old group` &#8594; `new group` on its own line.

### PR DESCRIPTION
**Pull request by jniles**
Adds the debtor group changes onto the patient financial activity as requested by our friends in Vanga.

Closes #5487.

Here is what it looks like:
image

### CODE REVIEW

**Review by lomamech — COMMENTED** [review]
image
I have just tested it by making several change of debtor group and it works well but I think that we could add in the patient's financial activity report the possibility of being able to select a debtor group

**Comment by lomamech** [comment]
> image
> I have just tested it by making several change of debtor group and it works well but I think that we could add in the patient's financial activity report the possibility of being able to select a debtor group

@jniles  Because I tell myself that users might ask for it someday, what do you think

**Comment by lomamech** [comment]
@jniles What do you think of the idea of updating the option to view the report by specifying the debtor group

**Comment by jniles** [comment]
> @jniles What do you think of the idea of updating the option to view the report by specifying the debtor group

I don't think that makes sense.  What information would that tell you?

Ideally, when a debtor changes group they should have their debt written off and that old account closed.  See https://github.com/IMA-WorldHealth/bhima/issues/2158.  So, even if the debtor group changed back then, it doesn't garantee that any of that debt is still in their account.  I'm not sure what a report filtered by debtor group would tell you.

**Comment by lomamech** [comment]
> > @jniles What do you think of the idea of updating the option to view the report by specifying the debtor group
> 
> I don't think that makes sense. What information would that tell you?
> 
> Ideally, when a debtor changes group they should have their debt written off and that old account closed. See #2158. So, even if the debtor group changed back then, it doesn't garantee that any of that debt is still in their account. I'm not sure what a report filtered by debtor group would tell you.

One day users might ask for it

**Pull request merged**
