### PR TITLE
chore: migrate bhChangeDepot to a component

### LINKED ISSUE #4787: Make bhChangeDepot into a component
We have a directive for changing depots called [`bhChangeDepot`](https://github.com/IMA-WorldHealth/bhima/blob/master/client/src/js/directives/bhChangeDepot.js).  In studying the code, there really isn't a good reason for it to be a directive instead of a component.  It would simplify the code (and make future migrations easier) if we went ahead and migrated this to a component.

### PR DESCRIPTION
**Pull request by jniles**
Changes the directive into a component for bhChangeDepot.

Closes #4787.

### CODE REVIEW

**Comment by jeremielodi** [comment]
It seems that travis fails

**Comment by jniles** [comment]
@jeremielodi yeah, I asked for a review too soon, I apologise.  I'll get this working and hit you up again.

**Review by jeremielodi — APPROVED** [review]
look_good_to_me

**Pull request merged**
