### PR TITLE
Refactor operating account report

### LINKED ISSUE #3263: Refactor operating account report
Report operating account should display the values of accounts of profits and expense accounts in absolute values except in case the expense accounts are creditor and profit accounts are debtors

### PR DESCRIPTION
**Pull request by lomamech**
- Refactor Operating Account display the values of accounts of profits and
  expense accounts in absolute values
- account balance by type_id and periods This function does exactly the same thing except the value of amount will be debit - credit this will know the expense account

closes #3263

### CODE REVIEW

**Comment by jniles** [comment]
Could you post a screenshot?

**Comment by lomamech** [comment]
operating

**Comment by jniles** [comment]
@lomamech, I'm not sure if this is tied to your PR, but the bottom of the report has "total of charges" as ($468,576.73) and total of profits as $616,083.72.  The result is $1,084,660.45.

But shouldn't it be: $-468,576.73 + $616,083.72 = $147,506.99?

**Comment by jniles** [comment]
@lomamech, let me know when you are done with your changes and ready for a review.  It is looking good so far!

**Pull request merged**
