### PR TITLE
feat(weekend configuration) add help message

### LINKED ISSUE #3102: Weekend Configuration needs explanatory text
The configuration of weekends seems to be confusing for our users - with good reason.  There isn't any text explaining how to use the module.  We should add it so that our users do not forget how the system behaves.  See below:

weekendconfigurationconfusion
_FIg 1: Weekend Configuration_

The user is supposed to click the days _that are weekend days_ or days that are not worked during the week.  We need a text that reads "Mark only the days that are not worked.  Unchecked days will be considered as working days in the payroll calculation."

### PR DESCRIPTION
**Pull request by jeremielodi**
closes #3102

### CODE REVIEW

**Comment by jniles** [comment]
Can you include a screenshot since this is just a UI change?

**Comment by jeremielodi** [comment]
weekend

**Comment by jniles** [comment]
Thanks!  Instead of putting the text in the modal-header, could you put it in the modal-body?  That way the modal looks like most other modals in the application.

**Comment by jniles** [comment]
This is what it looks like now:
weekendconfigurationconfusionresolved

bors r+

**Pull request merged**
