### PR TITLE
Fix invoice item validation CSS animation

### PR DESCRIPTION
**Pull request by sfount**
This commit removes the possibility of the `.hinge` animation being
applied in BHIMA. It is never intentionally used but seems to be applied
to ui-grid rows in a quirk of validation.

After investigating it looks like this quirk was introduced in the build process change on https://github.com/IMA-WorldHealth/bhima-2.X/pull/3123. It has been noted that glyphicons are not properly copied during this process, this style issue must be related but I cannot connect the two. 

The style deprecated here should be removed anyway but I will continue to investigate.

Expected patient invoice item validation behaviour: 
notfall

### CODE REVIEW

**Comment by jniles** [comment]
Well... I thought this was a fluke of our end to end tests when I first saw it.  It's a shame we can't figure out what the root cause of it is.

Great work catching this and tracking it down.

bors r+

**Comment by sfount** [comment]
Note that while this does fix the problem it looks like this problem was only introduced in https://github.com/IMA-WorldHealth/bhima-2.X/pull/3123. That means that fixing whatever is happening the build process will officially close https://github.com/IMA-WorldHealth/bhima-2.X/issues/3161. 

Then we could merge this as a refactor to prevent against this in the future!

bors r-

**Comment by sfount** [comment]
bors test

**Comment by jniles** [comment]
Do you mean "bors try"?

**Comment by sfount** [comment]
:man_facepalming: I prefer to use `test` to disambiguate from trying the pull request for crimes. 

This time though, 
bors try

**Pull request merged**
