### PR TITLE
fix(purchases): use prev price in optimal PO

### LINKED ISSUE #4326: Improvements to "Optimal Purchase Orders"
We have an "optimal purchase order" functionality in the purchase orders module that creates a purchase order based on your previous stock consumption.

Currently, all the price information for the optimal purchase order is blank.    We need to implement https://github.com/IMA-WorldHealth/bhima/issues/4119 for this optimal purchase order feature.  The prices should be pulled out of the most recent price information.  This will greatly assist our users who need to fill out multiple purchase orders.

There is also no loading indicator on the "optimal purchase order" button which makes it difficult to know what state the module is in on a slow connection.

### PR DESCRIPTION
**Pull request by jniles**
Adds the previous purchase price into the optimal purchase order
scenario. Also reduces the number of HTTP requests by removing the
Inventory service call from the purchase controller and simply using the
inventory items that are already in the PurchaseFormService.

It also fixes the migration script so that we can migrate IMCK/Vanga successfully.

Closes #4326.

Here is it in action:
bjqALdiEPF

### CODE REVIEW

**Comment by jniles** [comment]
@lomamech can I get a review?

**Review by lomamech — APPROVED** [review]
@jniles it works well, would it be possible to display the articles in alphabetical order

**Comment by jniles** [comment]
@lomamech, sure, will do.

**Comment by jniles** [comment]
@lomamech, this is done.

FDosJYlFrm

**Pull request merged**
