### PR TITLE
chore(xlsx): clean up renderer code

### PR DESCRIPTION
**Pull request by jniles**
Formats the code, comments it, and uses lodash instead of custom loops to reduce the surface area of code.  It also names the worksheet based on the report name.

### CODE REVIEW

**Comment by jniles** [comment]
@jeremielodi can you give me a review?

**Comment by jniles** [comment]
@jeremielodi ?

**Comment by jeremielodi** [comment]
I'm giving you a review

**Review by jeremielodi — APPROVED** [review]
LGTM

**Pull request merged**
