### PR TITLE
ci: use latest chrome for E2E tests

### PR DESCRIPTION
**Pull request by jniles**
Updates travis CI to no longer filter on a particular chromedriver. Should use the latest chrome browser for tests.

### CODE REVIEW

**Review by jmcameron — APPROVED** [review]
This seems like a safe PR.  But I have no way to test it.  
I suggest pushing it through and then try doing 'bors try' on some of our pending PRs to see what happens.  We can always do another PR to undo this if necessary.

**Comment by jniles** [comment]
bors try

**Comment by jniles** [comment]
Bors try

**Comment by jniles** [comment]
bors try

**Pull request closed without merging**
