### PR TITLE
feat(cashflowByService): filter by cashbox

### LINKED ISSUE #2807: Budget vs Balance Report
An important report for managers and financial analysts is the budget versus balance report.  Note that the report depends upon the implementation of #267.

### Budget versus Balance
The budget versus balance report is very similar to the Profit and Loss Statement.  It concerns only income and expense accounts.  The idea is to compare the income and expense accounts against what the budget has for the income and expense accounts.  Importantly, the report should show the variance between what has been budgeted and what was actually received.

### PR DESCRIPTION
**Pull request by jniles**
This commit implements cashbox filtering on the cashflow by service
report.  To accomadate this, the bh-cashbox-select component has been
refreshed to send the user_id if the component is restricted to the
user.

Closes #2807.

### CODE REVIEW

**Comment by lomamech** [comment]
Hi jonathan, I just tested this module and I have only two comments, 
- It would be necessary to add on the head of the report the name of cashbox the selected 

cashflowservice

- In Cash Flow Physical Report it is possible to select more cashboxes at the same time for the report, consider that for Cashbox By Service you can only use one Cashbox at a time.

**Comment by jniles** [comment]
@lomamech, thanks for the review!  I will make those changes and let you know when they are done.

**Comment by jniles** [comment]
@lomamech, the Cashflow by Service is supposed to model the ventillation which only looks at a single cashbox.  Does IMCK want us to try and support multiple cashboxes?

**Comment by jniles** [comment]
Changes have landed!  Here's what it looks like:
newcashflowbyservicepresentation
_Fig 1: New presentation of Cashflow By Service_

**Comment by lomamech** [comment]
@jniles  Travis CI build failed

**Comment by lomamech** [comment]
@jniles I try again but The Travis CI Buil Failed again, Try to discover the problem

**Comment by sfount** [comment]
I'm not 100% but it looks like this PR accidentally references and closes #2807 instead of #2805. I will update these issues accordingly, please revert this if this was intended.

**Pull request merged**
