### PR TITLE
docs: add barcode generation documentation

### PR DESCRIPTION
**Pull request by jniles**
Adds barcode generation documentation for developers.

-----
[View rendered docs/en/for-developers/barcodes.md](https://github.com/jniles/bhima/blob/docs-barcode-for-developers/docs/en/for-developers/barcodes.md)
[View rendered docs/en/for-developers/index.md](https://github.com/jniles/bhima/blob/docs-barcode-for-developers/docs/en/for-developers/index.md)

### CODE REVIEW

**Comment by jniles** [comment]
@jmcameron would you mind looking over this?  Any questions you have can yield improvements.

Since you are tackling #4273, this may prove useful to understanding that task.

**Comment by jmcameron** [comment]
Yes, I'll review this today.

**Comment by jmcameron** [comment]
This writeup is good and useful.   

A minor point:  In the barcode doc, I noticed that you give hyperlinks to lines of code.  Since line numbers in code will change, I suggest just referencing the file, not a line within.  In the first one,
   The code is found in server/lib/barcode.js.
I like the way that you spelled out the filename. That way I can browse my own code locally (not in github) and find the spot for a closer look.  However, the second one is a link without a filename, so I suggest you spell out the filename and make the link to the file, not a line within.

**Comment by jniles** [comment]
@jmcameron thanks for the review.  I'll make the changes for sure.  If anything confusing comes up during your work on barcodes, it's a good opportunity for one of us to add in the details.

**Comment by jniles** [comment]
@jmcameron changes landed.  Let me know what you think.

**Comment by jmcameron** [comment]
The barcode document looks good.  I actually used it to figure out how your Voucher example worked.  It is ready to go!

**Comment by jniles** [comment]
Bors r+

**Pull request merged**
