### PR TITLE
Feat(user grid) display assigned depots

### LINKED ISSUE #4021: Add "Caisse" and "Depot" columns to the user management grid.
We previously added a very useful column called "roles" to the user management grid.  This allows us to see, at a glance, which users have what roles, and filter on them.  Let's add two more columns:

 1. Depot - the depots each user has access to
 2. Caisse - the caisses each user has access to

It would go here:
image

### PR DESCRIPTION
**Pull request by jeremielodi**
closes #4021

### CODE REVIEW

**Comment by mbayopanda** [comment]
Is it possible to have resizable columns with the user grid

**Review by jniles — APPROVED** [review]
Looks good to me.  I think we probably will want to rewrite this in the future to use `GROUP_CONCAT()` to reduce complexity.  For the moment, this fulfills the issue though.

**Review by mbayopanda — APPROVED** [review]
bors r+

**Pull request merged**
