### PR TITLE
Add admin privilege for /users routes

### PR DESCRIPTION
**Pull request by mbayopanda**
This PR adds a middleware for checking user status for getting access to /users endpoints

### CODE REVIEW

**Comment by jeremielodi** [comment]
Another way to solve this will be to add a permission file in ```/server/controllers/admin/```


```js

const role = require('./role');
const constant = require('../../lib/constant.json');

function formateAPI(actionId) {

  function middleware(req, res, next) {
    role.isAllowed({
      actionId,
      userId: req.session.user.id
    }).then(permision => {
      if (permision) {
        return next()
      }
      sendError(res);
    }).catch(() => {
      serverError(res);
    })
  }
  return middleware;
}


function sendError(res) {
  res.status(401).json({
    title: "PERMISSION_DENIED",
    msg: 'You are not allowed to perfom this action'
  });
}

function serverError(res) {
  res.status(500).json({
    title: "INTERNAL_SERVER_ERROR",
    msg: 'An error occured while checking your permissions'
  });
}
module.exports = {
  createUser: formateAPI(constant.ACTIONS.CAN_CREATE_USER),
}

```


After that can use middlewares exposed in permissions file for you secured routes (APIs)


You must know that we use ```roles``` and  ```actions``` for security in BHIMA, it's more generic.

**Comment by mbayopanda** [comment]
@jeremielodi si tu as le temps, peux-tu tester ce PR ?

**Comment by jniles** [comment]
Hi team,

I just upgraded a production site and ran into an issue where all the previous administrators were locked out of the `/users` page.  Previously we had done this kind of manipulation using the concept of roles.  Is it possible to reimplement this functionality in roles?  Or at least clarify how the `is_admin` tag interacts with roles?

**Comment by jeremielodi** [comment]
Hello @jniles, solved this problem using roles and actions. you can see my code on  <a href="https://github.com/IMA-WorldHealth/jericho/blob/5d569f22a0f00fcac6070cf07889223274d952ae/server/routes.js#L53C1-L53C1"> ePRF </a>.
```js


app.post('/users',permissions.createUser, setting.user.create);
app.put('/users/:id',permissions.createUser,setting.user.update);
app.delete('/users/:id',permissions.createUser, setting.user.delete);

```

This is how I check permissions : <a href="https://github.com/IMA-WorldHealth/jericho/blob/main/server/controller/setting/permissions.js"> server/controller/setting/permissions.js</a>

```js


const role = require('./role');
const constant = require('../../lib/constant.json');

function formatAPI(actionId) {

  function middleware(req, res, next) {
    role.isAllowed({
      actionId,
      userId: req.session.user.id
    }).then(permision => {
      if (permision) {
        return next()
      }
      sendError(res);
    }).catch(() => {
      serverError(res);
    })
  }
  return middleware;
}


function sendError(res) {
  res.status(401).json({
    title: "PERMISSION_DENIED",
    msg: 'You are not allowed to perfom this action'
  });
}

function serverError(res) {
  res.status(500).json({
    title: "INTERNAL_SERVER_ERROR",
    msg: 'An error occured while checking your permissions'
  });
}

module.exports = {
  createUser: formatAPI(constant.ACTIONS.CAN_CREATE_USER),
  deleteEmployee: formatAPI(constant.ACTIONS.CAN_DELETE_EMPLOYEE),
  createEmployee: formatAPI(constant.ACTIONS.CAN_CREATE_EMPLOYEE),
  createOffice: formatAPI(constant.ACTIONS.CAN_CREATE_OFFICE),
  createPerdiems: formatAPI(constant.ACTIONS.CAN_CREATE_PERDIEM_LODGING),
  addBudgetLines: formatAPI(constant.ACTIONS.CAN_CREATE_BUDGET_LINES),
}




```

Actions are defined in the server constant file:

```json

{
    "DOCUMENT_STATUS": {
        "PENDING": 1,
        "SIGNED": 2,
        "APPROVED": 3,
        "CLOSED": 4,
        "DELETED":5
    },
    "VOUCHER_TUPES" : {
        "PRF" : 1,
        "DDF" : 2,
        "EXR" :3
    },
    "VOUCHER_TYPE" : {
        "PRF": 1,
        "DDF": 2,
        "EXR": 3,
        "OCH": 4,
        "TA": 5,
        "PYR": 6,
        "PYR_CHECK_LIST": 7,
        "MOR": 8
      },
    "ACTIONS" : {
        "CAN_EDIT_ROLE": 1,
        "CAN_RESET_PASSWORD": 2,
        "CAN_DELETE_EMPLOYEE": 3,
        "CAN_CREATE_EMPLOYEE": 4,
        "CAN_CREATE_BUDGET_LINES": 5,
        "CAN_CREATE_PERDIEM_LODGING": 6,
        "CAN_CREATE_OFFICE": 7,
        "CAN_CREATE_USER": 8,
        "CAN_CREATE_MISSION_ORDER":9
      }
}

```

**Pull request merged**
