### PR TITLE
chore(test): use browser.setLocation()

### LINKED ISSUE #380: Use `browser.setLocation()` instead of `browser.get()` for e2e tests
Our end to end test structure recently got a speedup in #351 by replacing `beforeEach()` with `before()`, ensuring the browser only loads the module at the beginning of the test, and does not refresh the module within the test suite.

Now, we can optimize the actual function called in the `before()` call.  Previously, we used the following code:

``` js
before(() => browser.get('#/some/route'));
```

This works fine, but is inefficient.  According to the protractor API documentation for [browser.get()](http://angular.github.io/protractor/#/api?view=Protractor.prototype.get), this navigates and loads the target page.  From our testing experience, this completely reloads the page, similar to `browser.refresh()`.

A more natural way to navigate is by changing the `$location` URL, as Angular does.  This is more efficient since it does not require the browser to refresh the page.  It also is reflective of how our application behaves.  Protractor exposes a method [browser.setLocation()](http://angular.github.io/protractor/#/api?view=Protractor.prototype.setLocation) that performs navigation based on the URL hash.   We can therefore change all our `before()` functions to:

``` js
before(() => browser.setLocation('some/route'));
```

This has already been demonstrated in an upcoming pull request [here](https://github.com/IMA-WorldHealth/bhima-2.X/pull/378/files#diff-225c1021c869b5120019692bf2f475aaR22).  If we apply this across all our tests, we will likely receive another performance boost.

### PR DESCRIPTION
**Pull request by jniles**
This commit changes all tests to use `helpers.navigate()`, which is an alias for `browser.setLocation()` for navigation.  This has performance advantages since it not longer requires app to download and parse the page as `browser.get()` does.

Additionally, the incorrect JSDoc syntax `@params` has been replaced with `@param` wherever it can be found.

Closes #380.

---

Thank you for contributing!

Before submitting this pull request, please verify that you have:
- [x] Run your code through JSHint.  [Check out our styleguide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/STYLEGUIDE.md).
- [x] Run integration tests.
- [x] Run end-to-end tests.
- [x] Accurately described the changes your are making in this pull request.

For a more detailed checklist, [see the official review checklist](https://docs.google.com/document/d/1nupLVLRXgSZJQo_acLgrwvPnN8RukfSiwRhSToj81uU/pub) that this PR will be evaluated against.

Ensuring that the above checkboxes are completed will help speed the review process and help build a stronger application.  Thanks!

### CODE REVIEW

**Comment by jniles** [comment]
@sfount, can I get a review?

**Comment by jniles** [comment]
Ping @sfount.

**Comment by sfount** [comment]
At some point we should start generating documentation as part of the main build so that we can catch mistakes like `@params` -> `@param`. This LGTM.

**Comment by sfount** [comment]
@jniles  Did you do any performance differences between `get()` and `setLocation()`? That would be interesting to see.

**Comment by jniles** [comment]
No, no real performance testing.  We could do some, but I am not sure if the time spent trying to do performance testing would be worth the time taken away from writing code...

**Comment by sfount** [comment]
Running `time` before and `time` after doesn't have to take any additional time away from writing code - end to end tests are routinely run anyway. This isn't a problem I was just curious.

**Pull request merged**
