### PR TITLE
fix(stock exit): fix unit cost and validation in lot modal

### PR DESCRIPTION
**Pull request by mbayopanda**
This PR fix : 
- The consideration of unit_cost in lot modal
- The validation of total lot quantity with the global quantity given in lot modal

### CODE REVIEW

**Comment by mbayopanda** [comment]
@jniles could you review this PR please

**Review by jniles — APPROVED** [review]
Looks fine to me.

bors r+

**Comment by mbayopanda** [comment]
@jniles could you review and bors it please

**Comment by jniles** [comment]
@mbayopanda, it looks like you've changed the API of StockEntryForm.  Could you add a unit test to [the stock entry form unit tests](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/test/client-unit/services/StockEntryModalForm.spec.js) to show that the `setMaxQuantity()` method will block validation if necessary?

**Comment by jniles** [comment]
Well done.  LGTM.

Bors r+

**Pull request merged**
