### PR TITLE
feature(Stock Movement)

### LINKED ISSUE #4297: Make the "Reference" column in Stock Movements link it the PDF receipt
The stock movements registry has a reference column that we could use to easily click on and view the document associated with that stock movement.  See below:
image

This behavior should be similar to the other registries.

### PR DESCRIPTION
**Pull request by lomamech**
- Make the reference in stock movement link to PDF receipt

closes #4297

### CODE REVIEW

**Comment by jniles** [comment]
@lomamech I can't figure out where this is.  Can you post a screenshot?

**Comment by lomamech** [comment]
> @lomamech I can't figure out where this is. Can you post a screenshot?

**Comment by lomamech** [comment]
> @lomamech I can't figure out where this is. Can you post a screenshot?

J3jKodRSQd

**Comment by jniles** [comment]
LGTM.  

bors r+

**Pull request merged**
