### PR TITLE
chore: clean up roles code

### PR DESCRIPTION
**Pull request by jniles**
This commit cleans up the roles code to remove extraneous lines and make them a bit more readable.

### CODE REVIEW

**Comment by jniles** [comment]
@jeremielodi, this is ready for a review.

**Comment by jniles** [comment]
@jeremielodi, could I get a review?

**Comment by jeremielodi** [comment]
ok I'm working on it

**Review by jeremielodi — COMMENTED** [review]
@jeremielodi approved this PR
Good job @jniles !

**Pull request merged**
