### PR TITLE
fix(debtors): ensure longest description shown

### LINKED ISSUE #4361: Show full invoice description instead of "Rounding Exchange Rate" in Patient Financial Activity
I came across a confusing thing during my analysis of the IMCK database.  There was an invoice that had a rounding of 88$, which led me to believe we had a rounding bug.   Here is what it looks like:
image

This actually is not a rounding bug - if the patient is referenced multiple times in the same transaction, we randomly choose which text to show in the group by.

Here is the full transaction:
image

So, rather than saying **Rounding Exchange Rate**, it would be better to show **Facture de Vicky Tshiyoyo Kena (PA.PAX.3957) pour 17 items dans le service Dispensaire Pax**.  This would make our reports look much more intelligible.

### PR DESCRIPTION
**Pull request by jniles**
This commit ensures that the longest description available to the user is displayed on reports such as the patient financial activity.  The longest description usually has the most detail.

Closes #4361.

**Before**
image

**After**
image

### CODE REVIEW

**Review by mbayopanda — APPROVED** [review]
@jniles the code looks good to me, maybe we need this feature also in the `Simple Account Report` to.

bors r+

**Comment by mbayopanda** [comment]
bors try

**Comment by jniles** [comment]
bors try

**Pull request merged**
