### PR TITLE
feat(deps): use yarn on Travis

### LINKED ISSUE #880: (build) use yarn instead of NPM for packages
A faster new alternative to NPM was developed by Facebook called [yarn](https://github.com/yarnpkg/yarn).  Probably the largest advantage is speed - [the benchmarks](https://www.berriart.com/blog/2016/10/npm-yarn-benchmark/) place it at 2-3 times faster than npm.

You can try it out by installing it with [windows](https://yarnpkg.com/en/docs/install#windows-tab) or [linux](https://yarnpkg.com/en/docs/install#linux-tab).

@IMA-WorldHealth/bhima-core what do you think?

### PR DESCRIPTION
**Pull request by jniles**
In order to get reproducible builds, we need a deterministic build
system like yarn.  Note that this change allows programmers to continue
to use npm alongside yarn without any issue.  However, yarn will be used
on Travis CI, respecting the yarn.lock file.

Closes #880.

For more information, see [Installing Yarn](https://yarnpkg.com/en/docs/install) and [Migrating from NPM to Yarn](https://yarnpkg.com/lang/en/docs/migrating-from-npm/)

### CODE REVIEW

**Review by sfount — APPROVED** [review]

**Comment by sfount** [comment]
This looks like a step in the right direction! All tests pass so this should be good to go - if any developers have problems with their builds we can review the migration process for this.

**Comment by jniles** [comment]
Hmm... bors seems to have halted.

**Comment by jniles** [comment]
bors r=sfount

**Comment by jniles** [comment]
bors r=sfount

**Pull request merged**
