### PR TITLE
feature : Cashflow report improvement

### LINKED ISSUE #7675: Add Feature: Group Accounts into Categories for a Synthetic Cash Flow Report
To enhance our financial management system, we propose categorizing the debtor group into two distinct categories: Insolvent and Solvent. This categorization will allow for more precise tracking, reporting, and decision-making regarding outstanding debts.
- Improved Risk Management: Differentiating between insolvent and solvent debtors will help the team assess financial risks more effectively, enabling more strategic planning and interventions.
- Optimized Collection Strategies: By identifying which debtors are insolvent, we can tailor our collection strategies to focus efforts on recovering debts from solvent entities, improving overall efficiency.
- Enhanced Reporting Accuracy: Categorizing debtors allows for clearer and more accurate financial reporting, which is crucial for internal audits and external stakeholder communication.
- Legal Compliance: Proper categorization ensures compliance with relevant financial regulations and standards, reducing the risk of legal complications.

### PR DESCRIPTION
**Pull request by lomamech**
- Added the ability to view reports by transaction types and account grouping.
- Two new account reference types were added for income and expenses.
- Enabling the display of both global and summary reports based on account groupings.

closes #7675

### CODE REVIEW

**Comment by lomamech** [comment]
**HOW TO TEST NEW FEATURES**

To be able to test these modules with the test database, it will first be necessary to create the grouping of account references related to the cash flow.

Accounting analysis:

The creation of this grouping is essential to ensure the consistency of financial data and to facilitate the analysis of cash flows. Accounts related to cash flow must be properly associated to guarantee an accurate overview of cash inflows and outflows. This also helps identify potential discrepancies in cash flow forecasts and effectively manage working capital needs.

**Comment by lomamech** [comment]
Simply go to the Administration Menu and configure the following account groupings.
image
_For groupings with reference types **Expense Cashflow**_
1. **Achat marchandises** with accounts **601**
image
2. **Charges Administratif** with accounts **605, 61, 62, 65**
image
3. **Charges personnel** with accounts 66
image
4.**Impôt et taxes** with accounts  64
image

**Comment by lomamech** [comment]
_For groupings with reference types **Income Cashflow**_
1. **Ventes biens et services** with accounts **701, 706**
image
2. **Subventions** with accounts *71*
image
3. **Autre produits** with accounts *75*
image

**Comment by lomamech** [comment]
To begin the test, it is first necessary to unblock the following debtor group.
- Updated Debtor Group
- Locked Debtor Group

**Comment by lomamech** [comment]
[CASHFLOW GITHUB.pdf](https://github.com/user-attachments/files/17193749/CASHFLOW.GITHUB.pdf)
Next, the following transactions must be executed while adhering to the dates, accounts, and currencies.

**Comment by lomamech** [comment]
|   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
  | Date | Transaction Type | Description | Account | Debit (Source) | Credit (Source) | Currency |  
  | 2024-07-31 | Support Incomes | Subvention | 41111011 : NGO |   | $30 000 | United States Dollars |  
  | 2024-07-31 | Support Incomes | Subvention | 57110010 : Caisse Principale CDF | $30 000 |   | United States Dollars |  
  |   |   |   |   |   |   |   |  
  | Date | Transaction Type | Description | Account | Debit (Source) | Credit (Source) | Currency |  
  | 2024-08-01 | Purchases | Drugs | 60111011 : Achat Médicaments en Sirop | $850 |   | United States Dollars |  
  | 2024-08-01 | Purchases | Drugs | 60111010 : Achat   Médicaments en comprimés | $750 |   | United States Dollars |  
  | 2024-08-01 | Purchases | Drugs | 57120010 : Caisse   Principale USD |   | $1 600 | United States Dollars |  
  |   |   |   |   |   |   |   |  
  | Date | Transaction Type | Description | Account | Debit (Source) | Credit (Source) | Currency |  
  | 2024-08-06 | Salary Payment | Paiement | 66110011 :   Remunération Personnel | $15 000 |   | United States Dollars |  
  | 2024-08-06 | Salary Payment | Paiement | 66411010 : Cotisation INSS (QPP) | $2 000 |   | United States Dollars |  
  | 2024-08-06 | Salary Payment | Paiement | 57120010 : Caisse Principale USD |   | $17 000 | United States Dollars |  
  |   |   |   |   |   |   |   |  
  | Date | Transaction Type | Description | Account | Debit (Source) | Credit (Source) | Currency |  
  | 2024-08-20 | Other Expenses | Transport | 57110010 : Caisse Principale CDF | 2 800 000 FC |   | Congolese Francs |  
  | 2024-08-20 | Other Expenses | Transport | 61411010 : Transport   personnel |   | 2 800 000   FC | Congolese Francs |  
  |   |   |   |   |   |   |   |  
  | Date | Transaction Type | Description | Account | Debit (Source) | Credit (Source) | Currency |  
  | 2024-08-22 | Support Incomes | Support | 57120010 : Caisse Principale USD | $20 000 |   | United States Dollars |  
  | 2024-08-22 | Support Incomes | Support | 41111011 : NGO |   | $20 000 | United States Dollars |  
  |   |   |   |   |   |   |   |  
  | Date | Transaction Type | Description | Account | Debit (Source) | Credit (Source) | Currency |  
  | 2024-08-29 | Cash Payment | Vente | 57110010 : Caisse   Principale CDF | 14 000 000   FC |   | Congolese Francs |  
  | 2024-08-29 | Cash Payment | Vente | 41111001 : REGIDESO |   | 14 000 000   FC | Congolese Francs |  
  |   |   |   |   |   |   |   |  
  | Date | Transaction Type | Description | Account | Debit (Source) | Credit (Source) | Currency |  
  | 2024-08-30 | Cash Payment | Paiement | 57120010 : Caisse   Principale USD | $2 500 |   | United States Dollars |  
  | 2024-08-30 | Cash Payment | Paiement | 70611012 : Hospitalisation |   | $2 500 | United States Dollars |  
  |   |   |   |   |   |   |   |  
  | Date | Transaction Type | Description | Account | Debit (Source) | Credit (Source) | Currency |  
  | 2024-09-01 | Cash Payment | Vente | 70611010 :   Consultations |   | $3 500 | United States Dollars |  
  | 2024-09-01 | Cash Payment | Vente | 57120010 : Caisse Principale USD | $3 500 |   | United States Dollars |  
  |   |   |   |   |   |   |   |  
  | Date | Transaction Type | Description | Account | Debit (Source) | Credit (Source) | Currency |  
  | 2024-09-18 | Convention Payment | Convention | 41111011 : NGO |   | 56 000 000   FC | Congolese Francs |  
  | 2024-09-18 | Convention Payment | Convention | 57110010 : Caisse   Principale CDF | 56 000 000   FC |   | Congolese Francs |  
  |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |  
  | Date | Transaction Type | Description | Account | Debit (Source) | Credit (Source) | Currency |  
  | 2024-09-30 | Salary Payment | Salary | 66131010 : Indemnité   de congé |   | $2 000 | United States Dollars |  
  | 2024-09-30 | Salary Payment | Salary | 66311010 : Indemnités de logement |   | $500 | United States Dollars |  
  | 2024-09-30 | Salary Payment | Salary | 66110011 : Remunération Personnel |   | $7 500 | United States Dollars |  
  | 2024-09-30 | Salary Payment | Salary | 57120010 : Caisse Principale USD | $10 000 |   | United States Dollars |  
  |   |   |   |   |   |   |   |

**Comment by lomamech** [comment]
However, it is also possible to use other transactions or a database with multiple transactions. Don’t forget that it is essential to post the journal entries into the general ledger.

**Comment by lomamech** [comment]
Here is the main interface of the new Cashflow report, with new features.
For our demonstration, we will analyze the data from August 1, 2024, to September 30, 2024, based on the transactions we previously entered.
image

**Comment by lomamech** [comment]
**Report with option Analysis of cash accounts**
image

**Comment by lomamech** [comment]
**Report with option Analysis of associated accounts**
image

**Comment by lomamech** [comment]
**Report with option Analysis of transaction types**
image

**Comment by lomamech** [comment]
**Report with Global Account Grouping Analysis**
image

**Comment by lomamech** [comment]
**Report with Synthetic Account Grouping Analysis**
image

**Comment by lomamech** [comment]
@jniles @jmcameron I just finished this work, could you, if possible, review this pull request (PR)?

**Review by jmcameron — CHANGES_REQUESTED** [review]
I tested this (per directions) and it seems to work.  I got different numbers but I presume that is because of differences in which transactions were posted to the general ledger, etc.  

I did not find the "Cash Payment" transaction type indicated in the testing directions.

I took a casual look through the code and it seems fine.

There are a few problems that need to be addressed before merged:

1. There is a merge conflict with `server/models/migrations/next/migrate.sql`.  It needs to be fixed.

2. The end to end tests have a failure because two account reference types have been added.  The end-to-end test failure occurs here:
{9AA54CBD-855E-4ADC-945E-097B140860B8}
Note that once this is fixed, all tests pass.

3. Update to the latest dependencies in `master` if that has not already been done.

**Comment by lomamech** [comment]
@jmcameron  I just finished with the comments of your review

**Comment by jmcameron** [comment]
> @jmcameron I just finished with the comments of your review

Thanks for making these updates.

**Pull request merged**
