### PR TITLE
test(filters): add equals() array test

### LINKED ISSUE #4236: FilterParser needs more unit tests
As referenced in https://github.com/IMA-WorldHealth/bhima/pull/4214, we only have a couple of tests for the [lib/filter.js](https://github.com/IMA-WorldHealth/bhima/blob/8e8e8bf541ab3408a51cbec06ea8de7c379a68ea/server/lib/filter.js#L139) library.  We need to ensure that the array functionality is also tested in a unit test.  Any other coverage issues should also be addressed.

### PR DESCRIPTION
**Pull request by jniles**
Adds an array unit test for the equals() method of the filter parser library.

Closes #4236.

### CODE REVIEW

**Comment by jniles** [comment]
@jeremielodi can I get a review?

**Comment by jeremielodi** [comment]
okay, I'm working on it

**Review by jeremielodi — APPROVED** [review]
Tested and approved by @jeremielodi

**Pull request merged**
